### ISSUE TITLE
Get core gene sequences from the generated pangenome output files

### ISSUE THREAD

**Issue by shubavarshini** [gtonkinhill/panaroo#100]
Hi,
I used panaroo to generate a lot of pangenomes. Now I want to segregate the "core" genes into a separate file. The summary file gives me the number of genes segregated into core or accessary genome and I could not find any indicator in the gene_presence_absence(_roary).csv files. I'm not sure if I overlooked the files or did not understand the roary formats. Can you please tell me is there a way that I can look up and extract only the "core" gene sequences?
Thank you.

**Comment by gtonkinhill** [comment]
Hi,

At the moment there is not a flag in the presence/absence files and you would need to count the number of isolates per row manually. If you are after the sequences themselves I would recommend using the alignment flag when running panaroo.

This can be called as

```
panaroo -i /path/to/input/*gff -o /path/to/output --clean-mode strict -a core
```

Alternatively if you have already run the main pipeline you can just run the alignment stage using

```
panaroo-msa -o /path/to/output -a core
```

**Comment by shubavarshini** [comment]
Hi @gtonkinhill,

Can you please explain how panaroo-msa script works. What are the files from the pangenome output folders are being used and how?
I carried out an example and I see 3611 genes were chosen as core pangenomes. It would be helpful to understand how this number was chosen cause if I add up the core genes and soft core genes from the summary statistics it comes upto (3426+236) 3662 genes.

**Comment by gtonkinhill** [comment]
Hi, 

There was a small bug in the way the `summary_statistics.txt` file was calculated. This has been rectified in the latest version (dc8a961cfef8cbf5d5dc817beb0d1eea2486ef04).
The `panaroo-msa` script should work as expected with the `--core_threshold` parameter selecting the percentage of genomes a gene must be found in to be classified as core.

**Comment by shubavarshini** [comment]
Hi @gtonkinhill,
Sorry to be opening this issue again. As I have mentioned before, I'm trying to put together the core pangenome from the pan_genome_reference.fa . The panaroo-msa command does not help because it extracts all the gene sequences from each genome used to create the pangenomes. But I want the representative sequences that are present in pan_genome_reference.fa and are considered as core.
So to do that I wrote a small R script to pick all the gene names that could be present in >= 95% of the isolates. I use the gene_presence_absense_roary.csv file. For example, the pangenome I was working with had 3611 genes as core pangenomes. Now when I extract based on gene names, about 13 genes are missing from the pan_genome_reference.fa. Out of these 13, 10 are present in all the isolates. Can you please help me understand how do I pick these gene sequence from representative fasta file? Are there any other files generated by panaroo useful to do the same?

Looking further into issues I found #91 (https://github.com/gtonkinhill/panaroo/issues/91), and you said only one of the paralogous gene sequence is represented in the pan_genome_reference.fa. How do I know which sequences were represented for paralogs if the above genes were in fact paralogs?


Any information will be much better to understand panaroo's results. Thank you.
(P.S. using panaroo 1.2.2)
