### ISSUE TITLE
panaroo-qc: 

### ISSUE THREAD

**Issue by thorellk** [gtonkinhill/panaroo#103]
Hi! 

I am trying to run panaroo and have managed to run the main program without issues but when I try to run pararoo-qc I get the following log output:

```
panaroo-qc -i *.gff -o QC-results -t 1 --graph_type all --ref_db ~/reference_bact/refseq.genomes.k21s1000.msh
Traceback (most recent call last):
  File "/proj/uppstore2017270/conda_envs/panaroo_env/bin/panaroo-qc", line 10, in <module>
    sys.exit(main())
  File "/proj/uppstore2017270/conda_envs/panaroo_env/lib/python3.6/site-packages/panaroo/generate_qc_plots.py", line 441, in main
    ref_db=args.ref_db)
  File "/proj/uppstore2017270/conda_envs/panaroo_env/lib/python3.6/site-packages/panaroo/generate_qc_plots.py", line 350, in generate_qc_plot
    quiet=True)
  File "/proj/uppstore2017270/conda_envs/panaroo_env/lib/python3.6/site-packages/panaroo/generate_qc_plots.py", line 53, in get_mash_dist
    dist_mat[i, j] = float(d)
ValueError: could not convert string to float: 'version'
```

I am running on our university HPC where I downloaded panaroo using conda (the suggested version for multi-threading, `conda install -c bioconda/label/cf201901 panaroo` into a specific environment that I am running the code within.

Since the error is pointing to the get_mash_dist function I checked the `mash_dist.txt` output file and it looks like attached below. Seems like something has gone wrong in the execution of mash and more precisely with finding the database? I double checked by downloading the version that you refer to in the docs that the db itself should not be an issue.

Do you have any suggestions on what may be going on? Do I have to specify the path to the mash db in some other way?

[mash_dist.txt](https://github.com/gtonkinhill/panaroo/files/6131203/mash_dist.txt)

**Comment by gtonkinhill** [comment]
Hi,

Yes, this looks like it is caused by the version of `mash` you have installed. I would recommend installing at least version 2.1 or above. 

The multi-threading issue should now be resolved so it might be worth re-installing Panaroo using

```
conda install -c conda-forge -c bioconda -c defaults panaroo
```

This should hopefully install an updated version of mash.

**Comment by thorellk** [comment]
Hi! Thank you for your response! Yes, it seems like the version that were installed with panaroo was only 1.1. I now updated mash to v. 2.3 and it gets past that stage and I got output from at least the ngenes, ncontigs and MDS processes. However, I ran into some out of memory issues so I will try to run it with more cores but that is something that I should be able to solve myself :)
