### ISSUE TITLE
panaroo-gene-neibourhood needs plus-ultra

### ISSUE THREAD

**Issue by Leytoncito** [gtonkinhill/panaroo#104]
when I modify the final_graph.gml file the panaroo-gene-neighborhood script doesn't work well:
When I analyze the pangenome_reference.fa, ​​I see that several group_ "number" are interesting genes, I know this happens through the annotation, but I thought it would be a good idea to replace some group_ "number" with gene names. However this works well for single copy genes (two copies also works). this is great!! . But the problem is that I was doing the replacement of many "group_number" by IS families, consequently, I got to have many group_number by IS3 (for example), then when executing the panaroo-gene-neighborhood searched for the context of the IS3 gene , it only returns the genomic context of an IS3 and not of the 30 genes (for example).
What could I do in this case?
list the IS3 as IS3_1, IS3_2, IS3_3, ISn ...?
but I want them all in one table
If you can help me, it would be great, and I will be forever grateful.
PS: modify the .gml file with sed, was it ok ?????

**Comment by gtonkinhill** [comment]
Hi,

Yes, the `panaroo-gene-neighbourhood` function and most functions in Panaroo rely on the gene cluster names being unique. So one solution would be to do as you suggested and rename them IS3_1 ,IS3_2,...

You would then need to run the `panaroo-gene-neighbourhood` on each gene separately and concatenate the resulting tables. At the moment the script does not support searching for more than one gene at a time but we might change this in the future.

I don't see a reason why using `sed` wouldn't work but I think it might be easier to run the `panaroo-gene-neighbourhood` script using the original names and then simply rename the genes in the final concatenated table.

**Comment by Leytoncito** [comment]
Yes, I will do the last thing you suggested.
I will be careful.
Again thank you very much.
