### ISSUE TITLE
Using Panaroo on 1500 genomes (genome size ~4.5Mb)

### ISSUE THREAD

**Issue by MostafaYA** [gtonkinhill/panaroo#105]
Hi Gerry, thank you very much for this nice software.
I am trying to use Panaroo to identify the core genome of a genus. 
I started with a subsample of 100 genomes representative of all species in the genus. Panaroo ran perfectly. ~2000 genes were identified as the core genome. 
Next I wanted to scale it up, to use Panaroo on 1500 genomes from the same genus. Although I tried to use stringent criteria on genomes to be included, Panaroo has crashed at the step of  `collapse gene families...` 

I verified the taxonomy of strains with Kraken2 and also that the genome size did not drop below 3.5Mb for any strain included.  
 
This is the error
```
Traceback (most recent call last):
  File "/home/mostafa.abdel/tools/conda/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/mostafa.abdel/tools/conda/panaroo/lib/python3.8/site-packages/panaroo/__main__.py", line 340, in main
    G, distances_bwtn_centroids, centroid_to_index = collapse_families(
  File "/home/mostafa.abdel/tools/conda/panaroo/lib/python3.8/site-packages/panaroo/clean_network.py", line 141, in collapse_families
    seqid_to_index[sid] = centroid_to_index[seqid_to_centroid[sid]]
KeyError: '1328_14_76'
```
Help is very much appreciated. 
Can I use Panaroo on thousands of genomes?

Thanks a lot, 
Mostafa

Note: I can also share the data with you!

**Comment by gtonkinhill** [comment]
Hi Mostafa,

This is usually due to a strangely formatted annotation in one of the GFF files. More recent versions of Panaroo include the `--remove-invalid-genes` flag which can sometimes fix this issue.

Can you confirm which version of Panaroo you have by running

```
panaroo --version
```

**Comment by MostafaYA** [comment]
Hi Gerry, 
I am using version 1.2.3 of Panaroo (installed with conda).
I tried the option `--remove-invalid-genes` but still no success. Same error. 

My command was as follow: 
```
panaroo -i INPUT_FOLDER/*gff -o pangenome --clean-mode strict  --alignment core --aligner mafft --threads N --remove-invalid-genes
```

**Comment by gtonkinhill** [comment]
Hi Mostafa,

Could you reinstall the latest version of panaroo >= v1.2.4 ?

If this still fails to resolve the problem I would be happy to take a look if you are able to share a reproducible example. 

If you are able to narrow it down to a smaller set of genomes that cause the problem that would be great.

My email is gt4@sanger.ac.uk

**Comment by MostafaYA** [comment]
Hi Gerry, finally it worked. 
1. I updated to the latest version (v1.2.4) 
2. I filtered out ~ 200 genomes with more strigent data quality control criteria
3. I activated the flag `--remove-invalid-gene`

Thank you,
