### ISSUE TITLE
panaroo-qc is generating error

### ISSUE THREAD

**Issue by ali21049** [gtonkinhill/panaroo#106]
Hi gtonkinhill,
Thank you for developing such a nice tool.
I freshly installed panaroo using conda. I am trying to run panaroo-qc, however, getting following error

 <pre>panaroo-qc -i *.gff -o results -t 4 --graph_type all --ref_db refseq.genomes.k21s1000.msh 
Max p-value: 0
Loading Loading refseq.genomes.k21s1000.mshrefseq.genomes.k21s1000.mshLoading ......refseq.genomes.k21s1000.msh...Loading refseq.genomes.k21s1000.msh...

Killed
Killed
Killed
   16160796 distinct hashes.
Streaming from B_pumilus_ATCC_7061.gff...
   Estimated distinct k-mers in mixture: 3834663
Summing shared...
Reallocating to winners...
Computing coverage medians...
Writing output...
joblib.externals.loky.process_executor._RemoteTraceback: 
&quot;&quot;&quot;
Traceback (most recent call last):
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py&quot;, line 431, in _process_worker
    r = call_item()
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py&quot;, line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/_parallel_backends.py&quot;, line 595, in __call__
    return self.func(*args, **kwargs)
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/parallel.py&quot;, line 262, in __call__
    return [func(*args, **kwargs)
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/parallel.py&quot;, line 262, in &lt;listcomp&gt;
    return [func(*args, **kwargs)
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/generate_qc_plots.py&quot;, line 254, in run_mash_screen
    subprocess.run(temp_mash_cmd, shell=True, check=True)
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/subprocess.py&quot;, line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command &apos;mash screen -i 0.8 -w refseq.genomes.k21s1000.msh B_pumilus_CJC.gff &gt; /home/ali/Ali/panaroo_qc_data/results/tmp135m04mj&apos; returned non-zero exit status 137.
&quot;&quot;&quot;

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/home/ali/miniconda3/envs/panaroo/bin/panaroo-qc&quot;, line 10, in &lt;module&gt;
    sys.exit(main())
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/generate_qc_plots.py&quot;, line 437, in main
    generate_qc_plot(method=args.graph_type,
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/generate_qc_plots.py&quot;, line 371, in generate_qc_plot
    mash_contam_file = get_mash_contam(input_gffs=input_files,
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/panaroo/generate_qc_plots.py&quot;, line 276, in get_mash_contam
    genome_hits = Parallel(n_jobs=n_cpu)(
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/parallel.py&quot;, line 1054, in __call__
    self.retrieve()
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/parallel.py&quot;, line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/site-packages/joblib/_parallel_backends.py&quot;, line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/concurrent/futures/_base.py&quot;, line 432, in result
    return self.__get_result()
  File &quot;/home/ali/miniconda3/envs/panaroo/lib/python3.8/concurrent/futures/_base.py&quot;, line 388, in __get_result
    raise self._exception
subprocess.CalledProcessError: Command &apos;mash screen -i 0.8 -w refseq.genomes.k21s1000.msh B_pumilus_CJC.gff &gt; /home/ali/Ali/panaroo_qc_data/results/tmp135m04mj&apos; returned non-zero exit status 137.</pre>

**Comment by gtonkinhill** [comment]
Hi,

This looks like the program may have been killed by an external command. 

Are you able to run `mash` to check it runs okay. Assuming the files are in your working directory you could run

```
mash screen -i 0.8 -w refseq.genomes.k21s1000.msh B_pumilus_CJC.gff
```

**Comment by ali21049** [comment]
Fortunately, i had got results in spite of error.
By the way i ran mash screen -i 0.8 -w refseq.genomes.k21s1000.msh B_pumilus_CJC.gff and got
Loading refseq.genomes.k21s1000.msh...
Killed

**Comment by gtonkinhill** [comment]
I'm glad you were able to get results. As you got the same outcome when running Mash in isolation it looks like the issue is to do with how Mash is interacting with your server. I'm afraid I can't debug this further.
