### ISSUE TITLE
genes in partitions 

### ISSUE THREAD

**Issue by shn89** [gtonkinhill/panaroo#107]
Hi, 
Is it possible to get a list of the genes in each partition? As far as I can see it is only possible to see how many genes are in each in the summary_statistics, but not which genes. Of course it is possible to calculate from the presence/absence, but since there's a summary table this is probably already done but just not written.
Another thing, how come the isolates are numbered in cytoscape instead of using the passed isolate name, this would also make it easier to use. 
Best, Sofie

**Comment by gtonkinhill** [comment]
Hi,

As this information is already in the presence/absence matrix and as these partitions are somewhat arbitrary I'm not sure that enough people will need this feature. If more users request this I'm happy to revisit it in the future.

I'm hoping to include a much more thorough guide to post processing the outputs of Panaroo soon including a few new functions. This should hopefully make this easier in the future.

I agree that it would be good to have the original isolate names available in cytoscape. I will look into adding this in a future version.
