### ISSUE TITLE
panaroo-msa for pan genome alignment

### ISSUE THREAD

**Issue by ali21049** [gtonkinhill/panaroo#108]
Hi,
I am using panaroo, panaroo-msa is working fine for core genome alignment, however, i am getting the following error for pan-genome alignment

Traceback (most recent call last):
  File "/home/ali/.local/bin/panaroo-msa", line 33, in <module>
    sys.exit(load_entry_point('panaroo==1.2.6', 'console_scripts', 'panaroo-msa')())
  File "/home/ali/.local/lib/python3.6/site-packages/panaroo/post_run_alignment_gen.py", line 100, in main
    core_nodes = get_core_gene_nodes(G, args.core, len(args.input_files))
AttributeError: 'Namespace' object has no attribute 'input_files'

my command was
panaroo-msa -a pan -o ./results2/ -t 4

**Comment by ali21049** [comment]
i got a work around by decreasing the --corethreshold to 0.00 and -a core. So it will consider everything as core. I hope its not wrong!

**Comment by gtonkinhill** [comment]
Thanks for pointing this out. There is a bug in the post run `panaroo-msa` script which causes it to crash. I've pushed a fix in 883ede69182265430054921d611818149d0c1037 which should resolve the issue.
