### ISSUE TITLE
Pan_genome_reference.fa has less number of genes than pan genes in gene presence absense.csv

### ISSUE THREAD

**Issue by ali21049** [gtonkinhill/panaroo#109]
Just to highlight for improvement!!
Pan_genome_reference.fa has less number of genes than pan genes in gene presence absense.csv. However, The number of genes in summary file and gene presence absence are equal.

**Comment by gtonkinhill** [comment]
Hi,

Paralogous gene clusters are only represented in the `pan_genome_reference.fa` once to avoid issues when aligning reads to duplicated regions. This leads to the lower number of genes in the pseudo reference that you have observed.
