### ISSUE TITLE
Reopening issue #100

### ISSUE THREAD

**Issue by shubavarshini** [gtonkinhill/panaroo#110]
Hi @gtonkinhill,
Sorry to be opening this issue again. As I have mentioned before, I'm trying to put together the core pangenome from the pan_genome_reference.fa . The panaroo-msa command does not help because it extracts all the gene sequences from each genome used to create the pangenomes. But I want the representative sequences that are present in pan_genome_reference.fa and are considered as core.
So to do that I wrote a small R script to pick all the gene names that could be present in >= 95% of the isolates. I use the gene_presence_absense_roary.csv file. For example, the pangenome I was working with had 3611 genes as core pangenomes. Now when I extract based on gene names, about 13 genes are missing from the pan_genome_reference.fa. Out of these 13, 10 are present in all the isolates. Can you please help me understand how do I pick these gene sequence from representative fasta file? Are there any other files generated by panaroo useful to do the same?

Looking further into issues I found #91, and you said only one of the paralogous gene sequence is represented in the pan_genome_reference.fa. How do I know which sequences were represented for paralogs if the above genes were in fact paralogs?

Any information will be much better to understand panaroo's results. Thank you.
(P.S. using panaroo 1.2.2)

**Comment by gtonkinhill** [comment]
Hi,

Yes, we only include one copy of each paralogous cluster in the `pan_genome_reference.fa` file so it usually has fewer genes than are reported in the `summary_statistics.txt` file.

For your use case I would recommend using the `gene_presence_absence.csv` file to work out which gene clusters you are interested in. This also lists the corresponding sequence name for each gene in each cluster which will match that given in the `gene_data.csv` file. 

You can then choose a representative for each cluster and pull the sequence out of the entry in the `gene_data.csv` file. We typically choose the longest sequence as the representative if it has sufficient support.
