### ISSUE TITLE
Translation Table

### ISSUE THREAD

**Issue by MichWeb75** [gtonkinhill/panaroo#113]
Hi, 
I still have the issue with the translation table (Mycoplasma genomes require Table Nr.4 instead of 11) and I would like to solve it. I just need some information how you encoded the translation_Table np array in prokka.py
The difference is only TGA which is Amino Acid W instread of Stop . How to change the translation_table ? Thanks for your help!

```{python}
translation_table = np.array([[[b'K', b'N', b'K', b'N', b'X'],
```

File "/lib/python3.6/site-packages/panaroo/prokka.py", line 161, in translate_sequences
    raise ValueError("Premature stop codon in a gene!")
ValueError: Premature stop codon in a gene!

**Comment by gtonkinhill** [comment]
I've commented in #53 so will close this for now.
