### ISSUE TITLE
fasta headers affecting pangenome analysis

### ISSUE THREAD

**Issue by LeahRoberts** [gtonkinhill/panaroo#115]
Hi Gerry,

I had a look through some of the resolved/open issues and couldn't see this one - so I hope I'm not repeating anything.

I think I found a small bug that has something to do with the fasta headers in the genomes. I built a relatively small pangenome from 20 E. coli's (annotated with Prokka) and there were very few core genes (and genes overall):
```
Core genes	(99% <= strains <= 100%)	18
Soft core genes	(95% <= strains < 99%)	4
Shell genes	(15% <= strains < 95%)	440
Cloud genes	(0% <= strains < 15%)	1623
Total genes	(0% <= strains <= 100%)	2085
```
Weirdly I ran into this issue previously (using the same data hah) with Roary, and the way I fixed it was by editing the fasta headers. For the first run (with the above Panaroo output) most of the genomes I used looked something like this: 
```
CFT073.ref.fa
>CFT073
>1 2
>2 3
>3 4
>4 5

Escherichia_coli_MINF_7C.ref.fa
>0 chromosome
>1 plasmid1
>2 plasmid2

Escherichia_coli_MSB1_6C.ref.fa
>0 chromosome
>1 plasmid1
>2 plasmid2
```

I edited the headers to be consistent (and unique), like this: 

```
CFT073.ref.modified.fa
>CFT073.ref_1
>CFT073.ref_2
>CFT073.ref_3

Escherichia_coli_MINF_1A.ref.modified.fa
>Escherichia_coli_MINF_1A.ref_1
>Escherichia_coli_MINF_1A.ref_2
>Escherichia_coli_MINF_1A.ref_3
```

And this seemed to fix the problem - after only changing the headers, my Panaroo output is this: 

```
Core genes	(99% <= strains <= 100%)	3319
Soft core genes	(95% <= strains < 99%)	168
Shell genes	(15% <= strains < 95%)	3001
Cloud genes	(0% <= strains < 15%)	4764
Total genes	(0% <= strains <= 100%)	11252
```

I hope this is clear - basically in both cases Panaroo ran without flagging any errors, but with very different results. As the same thing happened with Roary, I'm wondering if it's some legacy code (or something in the Prokka gff?) that is causing the issue. 

Cheers

**Comment by gtonkinhill** [comment]
Hi Leah,

Sorry for being slow to get to this. I got distracted with some other work.

This was a tricky one. It looks like this is a weird quirk in Prokka. It seems to dislike fasta headers that start as `>0 `. It relabels these sequences as `SEQ` in the annotation section of the resulting gff file. This then causes `panaroo` and possibly `roary` to skip these annotations as they don't match with a sequence header. I've copied an example of the output below.

```
##gff-version 3
##sequence-region 0 1 526811
##sequence-region 1 1 500965
SEQ     Prodigal:002006 CDS     25      351     .       +       0       ID=AAJEMFJL_00001;inference=ab initio prediction:Prodigal:002006;locus_tag=AAJEMFJL_00001;product=unannotated protein
SEQ     Prodigal:002006 CDS     409     747     .       +       0       ID=AAJEMFJL_00002;inference=ab initio prediction:Prodigal:002006;locus_tag=AAJEMFJL_00002;product=unannotated protein
SEQ     Prodigal:002006 CDS     753     2168    .       -       0       ID=AAJEMFJL_00003;inference=ab initio prediction:Prodigal:002006;locus_tag=AAJEMFJL_00003;product=unannotated protein
.
.
.
.
##FASTA
>0
TACAACCTGCTGTTGGTGTCGCGTATGAAAGAAGAGCTGGGTGCCGGTATCAATACGGGC
ATCATTCGAGCGATGGGTGGGACCGGCAAAGTGGTCACCTCGGCGGGTCTGGTCTTCGCG
```

I've posted an issue to the prokka GitHub and will add a warning to the Panaroo documentation as well.

**Comment by LeahRoberts** [comment]
Hey Gerry,

Thanks for investigating, makes perfect sense. 

Cheers!
