### ISSUE TITLE
summary statistics and gene_presence_absence file are inconsistent

### ISSUE THREAD

**Issue by spencer411** [gtonkinhill/panaroo#116]
They don't match. I am working with 170 isolates. My summary statistics file is telling me there are 2030 core genes. Nevertheless looking at my gene_presence_absence file there are only 2013 genes within the 99% threshold I set. Does the summary statistics file just default to to the default core threshold despite what is entered when running the program or is something else going on here?

This is my code:
panaroo -t 96 -i *.gff -o panaroo_results --clean-mode strict -a core --aligner clustal --core_threshold 0.99

**Comment by gtonkinhill** [comment]
Hi,

Could you confirm which version of `panaroo` you are using? There was an issue with the `summary_statistics.txt` file which was addressed in commit 88ea7d994ecef5810848a99b7d9b16e12d0b3a3e. The latest version (1.2.7) should not have this problem.

The `--core_threshold` parameter does not affect the `summary_statistics.txt` file and is used instead in the core alignment stage of the pipeline.

**Comment by spencer411** [comment]
I have 1.2.2 installed. I will reinstall the latest version and give it a test. Thanks!

**Comment by spencer411** [comment]
just a question, for the older version, is the gene_presence_absence file correct? That is, can I just calculate my own summary statistics using it to avoid rerunning everything with the updated version of panaroo?

**Comment by spencer411** [comment]
Im all good it was a version issue, thanks!

**Comment by limrp** [comment]
Hi!

Sorry for reopening the issue. I installed the latest Panaroo and I ran this command:

`panaroo -i */*.gff3 -o ../../../results/phylogenomics/pangenome/ --clean-mode strict -a core --aligner mafft --core_threshold 0.98 --remove-invalid-genes --threads 13`

I set `--core_threshold 0.98`.

But in the `summary_statistics.txt` file I got this:

```
Core genes	(99% <= strains <= 100%)	3460
Soft core genes	(95% <= strains < 99%)	0
Shell genes	(15% <= strains < 95%)	3025
Cloud genes	(0% <= strains < 15%)	380
Total genes	(0% <= strains <= 100%)	6865
```

In the documentation it says:

>   --core_threshold CORE
>                         Core-genome sample threshold (default=0.95)

So I thought that setting the `--core_threshold` to 0.98 would make the core genes those present in between 98% and 100% of the strains. Something similar to this:

```
Core genes	(99% <= strains <= 100%)	
Soft core genes	(**98%** <= strains < 99%)	
```

With 98% being the lower threshold for the sofe core genes. But in the `summary_statistics.txt`, the default value (0.95) is still being used. 

Please, I'm new to this analysis and I'll be very grateful for your help in clarifying my confusion in this issue :)
