### ISSUE TITLE
Missing genomes in output

### ISSUE THREAD

**Issue by iferres** [gtonkinhill/panaroo#117]
Hi, I'm having an issue with the output of panaroo. There're 2 missing genomes (all their genes) in the gene_presence_absence.csv file. It seems to be loosing them at some point after the cd-hit step. The columns for each genome appear empty, i.e. I can't find any genes for some of the genomes.

Find the gffs inside the "sim_1.25E12_rep1" directory. See the missing genome1 and genome7 genes. All of these are simulated gff, the structure is a bit strange but panaroo seems to cope fine with them, it is just missing all the genes from those 2.

[example_gffs_panaroo.tar.gz](https://github.com/gtonkinhill/panaroo/files/6576901/example_gffs_panaroo.tar.gz)

I ran it as follows (v.1.2.7, installed with conda):
```
panaroo --clean-mode strict -t 4 -o panaroo_strict_sim_1.25E12_rep1 -i *.gff
```

Not sure if I am doing something wrong.

Great tool by the way, congrats and thank you!

**Comment by gtonkinhill** [comment]
Hi,

It looks like you have simulated a single gene per contig. Panaroo relies heavily on synteny information.
In its `strict` mode it will often treat diverse genes with no contextual support as errors or contamination. This can be disable by using the `sensitive` mode but panaroo should not really be used to cluster genes that aren't part of assembled genomes.

**Comment by iferres** [comment]
I see, I suspected that but wasn't sure. I will try to improve the simulations. 
Thanks!

**Comment by iferres** [comment]
One last related question, do you have available the gff files simulated (after the assembly and prokka annotation) in the panaroo paper?

**Comment by gtonkinhill** [comment]
Hi,

Most of the data used in the paper should be available on [zenodo](https://zenodo.org/record/3599800) or from one of the releases on the [GitHub](https://github.com/gtonkinhill/panaroo_manuscript) repository for the paper.

There are also a few scripts in the panaroo GitHub under the `scripts` folder for simulating pangenomes. Most of them start with `pseudo`. 

I hope this helps!

**Comment by iferres** [comment]
Thanks!
