### ISSUE TITLE
pan_genome_reference.fa sequence origins

### ISSUE THREAD

**Issue by lillycummins** [gtonkinhill/panaroo#118]
Hi :)

Is there any way to be able to find out which genome a sequence included in the reference.fa has been taken from?
(e.g. similar to the seq IDs that is provided in the equivalent roary file)

**Comment by gtonkinhill** [comment]
Hi,

This isn't currently recorded but the sequences should map directly to those given in the `gene_data.csv` file.
I've copied a small (relatively untested) python code snippet that should pull out this association. It can return multiple genomes when the same gene has an identical sequence in multiple genomes.

```
import pyfastx

ref_seqs = {}
for name, seq in pyfastx.Fasta('pan_genome_reference.fa', build_index=False):
    ref_seqs[seq] = [name]

with open('gene_data.csv', 'r') as infile:
    next(infile)
    for line in infile:
        line=line.split(',')
        genome, seq = line[0], line[5]
        if seq in ref_seqs:
            ref_seqs[seq].append(genome)

with open('ref_seq_genome.csv', 'w') as outfile:
    for seq in ref_seqs:
        outfile.write(','.join(ref_seqs[seq])+'\n')
```
