### ISSUE TITLE
Allow Genbank file input instead of jus GFF?

### ISSUE THREAD

**Issue by tseemann** [gtonkinhill/panaroo#119]
Hi Gerry

Any chance you could add Genbank file input support?

This would be very handy when dealing with Refseq data because NCBI GFF ar4re different to Prokka ones.

Torsten

**Comment by gtonkinhill** [comment]
Hi Torsten,

Yes, this is a good suggestion and I will try and add support for Genbank files in the near future.

In case it's helpful, we do currently include a script that attempts to convert RefSeq GFFs into the correct input for Panaroo `scripts/convert_refseq_to_prokka_gff.py`

**Comment by gtonkinhill** [comment]
Hi Torsten,

I have finally added support for Genbank and Bakta (seperate GFF/Fasta files) to Panaroo in version 1.3.0.
