### ISSUE TITLE
Core genome alignment threshold = 1.0 fails

### ISSUE THREAD

**Issue by cizydorczyk** [gtonkinhill/panaroo#121]
Hello,

When running panaroo-msa (v. 1.2.7), when I set the --core_threshold parameter to 1 (or 1.0), I get an empty core_genome_alignment.aln file, a truncated .embl file, and no aligned genes. The whole run seems to fail:

```
(panaroo-1.2.7) $ panaroo-msa -o ~/hinfluenzae/i35_gwas/panaroo/panaroo_output/ -t 8 -a core --aligner mafft --core_threshold 1
0it [00:00, ?it/s]
0it [00:00, ?it/s]
```

It works just fine if I set the core threshold to say, 0.95.

I also get an empty core genome alignment file if I run the entire Panaroo pipeline, setting the core threshold to 1.

Is it possible to include only genes present in 100% of samples in the core alignment?

Thanks.

**Comment by gtonkinhill** [comment]
Hi,

Panaroo requires that the gene is seen in strictly more than the `--core_threshold` provided. I.e `x > threshold`.
To get 100% you will need to specify a threshold close to but not equal to 1. i.e 0.999 would work for any dataset with less than a thousand genomes.
