### ISSUE TITLE
networkx.exception.NetworkXError: [] is not a string

### ISSUE THREAD

**Issue by alexmsalmeida** [gtonkinhill/panaroo#122]
Hi,

I am generating pan-genomes for about ~3,200 species, and have managed to successfully generate a pan-genome for pretty much all of them. However, there are about 20 species that are always giving me the error indicated below:

```
writing output...
Traceback (most recent call last):
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/lib/python3.7/site-packages/panaroo/__main__.py", l
ine 466, in main
    nx.write_gml(G, args.output_dir + "final_graph.gml")
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/lib/python3.7/site-packages/decorator.py", line 232
, in fun
    return caller(func, *(extras + args), **kw)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/lib/python3.7/site-packages/networkx/utils/decorato
rs.py", line 239, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/lib/python3.7/site-packages/networkx/readwrite/gml.
py", line 823, in write_gml
    for line in generate_gml(G, stringizer):
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/lib/python3.7/site-packages/networkx/readwrite/gml.
py", line 758, in generate_gml
    yield from stringize(attr, value, ignored_keys, "    ")
  File "/nfs/production/interpro/metagenomics/mags-scripts/miniconda3/envs/func-annot/lib/python3.7/site-packages/networkx/readwrite/gml.
py", line 719, in stringize
    raise NetworkXError(f"{value!r} is not a string")
networkx.exception.NetworkXError: [] is not a string
```

All the genomes across all the species I am running were annotated with Prokka and the ones that are failing cover a wide range of population sizes (some species have only a few hundred genomes, whereas others span a few thousand), so there is no obvious reason why only these 20 are not finishing successfully.

I am running Panaroo v1.2.7 with the following command:

`panaroo -t 32 -i genome_list.txt -o panaroo_out --clean-mode strict --merge_paralogs --core_threshold 0.90 -c 0.90 -f 0.5 --no_clean_edges --remove-invalid-genes`

Any ideas on what could be the issue? Thanks in advance for the help.

Alex

**Comment by gtonkinhill** [comment]
Hi Alex,

It looks like something is going on right at the end when Panaroo is trying to save the final graph. My initial guess would be that there might be a gene name that is causing an issue with networkx but it's hard to diagnose.

Would it be possible for you to send me a small example that leads to the problem? 

My email is gt4@sanger.ac.uk

**Comment by alexmsalmeida** [comment]
Hi Gerry,

Thanks for the prompt response. I have put two example directories with GFF files here: 
`http://ftp.ebi.ac.uk/pub/databases/metagenomics/genome_sets/panaroo_tests/`

Let me know if you manage to track down the issue.

Best,
Alex

**Comment by gtonkinhill** [comment]
Hi Alex,

Thanks for sharing the example data. It turns out this was caused by very rare instances of edges in the pangenome graph not being deleted when they were no longer supported by any genomes.

This resulted in an empty list of supported genomes which then led to the final GML file failing to be written.

I've hopefully fixed this issue and a couple of other problems in the latest commit fb171d7 to the devel branch. I have a couple of extra things to add and will issue an updated version of Panaroo.

Thanks very much for your help in identifying this issue.

**Comment by alexmsalmeida** [comment]
Excellent, thanks Gerry. I'll wait for your next release and will try out the fix. Will report back in case I encounter any other issues.

**Comment by gtonkinhill** [comment]
Thanks I've just made a release v1.2.8. Let me know if you run into any issues.
