### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by GM110Z** [gtonkinhill/panaroo#123]
Hello,

I am trying to run Panaroo on a set of 4000 genomes. I have successfully annotated them using prokka. However when I try to run :panaroo -i ./prokka_output/*/*.gff -o panaroo_output -t 2 --verbose -a core

but I get the error panaroo: Argument list too long.

Is there a way around it?

**Comment by gtonkinhill** [comment]
Hi,

Yes, you should be able to provide a list of files (one per line) instead. The command would then be 

```
panaroo -i my_file_list.txt -o panaroo_output -t 2 --verbose -a core
```

**Comment by GM110Z** [comment]
Thank you!
