### ISSUE TITLE
Fasttree phandango

### ISSUE THREAD

**Issue by MichWeb75** [gtonkinhill/panaroo#124]
Hi,
I would like to compare the resulting presence / absence tree from panaroo with that generated by roary.
Roary provides a P/A file called accessory_binary_genes.fa, which is used to generate a newick Fasttree.
This would be a very helpful extension for panaroo!

Best, 
Michael

**Comment by gtonkinhill** [comment]
Hi,

While we don't currently output this format it should be relatively straightforward to generate from the `gene_presence_absence.Rtab` file.

A neighbour joining tree can be generated in R using

```
library(data.table)
library(phangorn)
df <- fread("gene_presence_absence.Rtab",
              data.table = FALSE, drop = 1)

df <- as.matrix(df)
d <- 1/tcrossprod(df)
tree <- phangorn::NJ(d)
```
