### ISSUE TITLE
panaroo not reading my gff files

### ISSUE THREAD

**Issue by ngraned** [gtonkinhill/panaroo#125]
Hi, I tried to run panaroo but it cannot read my gff files, does the file need to be transferrd to the panaroo environment that was created?
panaroo -i ./resultsprokka/*.gff -o ./resultspanaroo/ -
-clean-mode moderate -a core --aligner clustal --core_threshold 0.98 -t 10
Traceback (most recent call last):
  File "/.conda/envs/Xcampestris_paper/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/.conda/envs/Xcampestris_paper/lib/python3.7/site-packages/panaroo/__main__.py", line 277, in main
    with open(args.input_files[0], 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: './resultsprokka/*.gff'

thanks

**Comment by gtonkinhill** [comment]
Hi,

It looks like you might be missing a `*`. Does the following work?

```
panaroo -i ./resultsprokka/*.gff -o ./resultspanaroo/ -
-clean-mode moderate -a core --aligner clustal --core_threshold 0.98 -t 10
```

**Comment by ngraned** [comment]
@gtonkinhill there is an * i even renamed it using results_ but see error below again
$ panaroo -i ./results_prokka/*.gff -o ./results_panaroo/ --clean-mode moderate -a core --aligner clustal --core_threshold 0.98 -t 10
Traceback (most recent call last):
  File "/.conda/envs/Xcampestris_paper/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/.conda/envs/Xcampestris_paper/lib/python3.7/site-packages/panaroo/__main__.py", line 277, in main
    with open(args.input_files[0], 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: './results_prokka/*.gff'

**Comment by ngraned** [comment]
the *is not showing when I send it here for some reason.

**Comment by gtonkinhill** [comment]
It looks like there is something wrong with the path to the files you are providing. What do you see if you run

```
head ./results_prokka/*.gff
```

**Comment by ngraned** [comment]
Yes, something was wrong with the path because the gff were in sub directories. I have fixed all that. panaroo is running now. thanks
