### ISSUE TITLE
panaroo-spydrpick, two small bug?

### ISSUE THREAD

**Issue by actledge** [gtonkinhill/panaroo#129]
I have installed the panaroo from conda.
And I use the following command:
panaroo-spydrpick -i gene_presence_absence.Rtab -o coevo_results --clusters mystrains_clusters.csv

get errors from this script:
panaroo/spydrpick.py
line 181:TypeError: only integer scalar arrays can be converted to a scalar index
and I tried to change this line of code to look like this:
from:
    max_hit_mis[i] = np.max(mis[hitsA == ids[i]])
to:
    max_hit_mis[i] = np.max(np.array(mis)[hitsA == ids[i]])
This seems to work...

and another error raised:
  File "/home/myusername/.conda/envs/panaroo/lib/python3.9/site-packages/panaroo/spydrpick.py", line 324, in main
    for i in np.argsort(-mis):
TypeError: bad operand type for unary -: 'tuple'
though I don't understand how the script works, but this part just seems to output a result, which is a series of numbers,
So I thought maybe this '-' was just a misinput...
I changed the line 324 from:
     for i in np.argsort(-mis):
to:
     for i in np.argsort(mis):
then I seemed to get the result, without error raised.

But since I'm just a rookie, and I don't fully understand how this script works, I'm not sure if it's ok.

**Comment by gtonkinhill** [comment]
Hi,

Thanks for flagging this. It was indeed caused by a recent change to using lists in place of numpy arrays in a few places.

The latest version on the development branch should resolve this issue. It can be installed using

```
pip install git+https://github.com/gtonkinhill/panaroo.git@devel
```

**Comment by gavinmdouglas** [comment]
I can confirm that this change to the dev branch seems to fix those bugs. Another bug I came across is that this error occurs if there are no significant hits returned by the `spydrpick` function. Specifically, it seems to occur if the three lists passed to `tukey_outlier` are empty.

```
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by gtonkinhill** [comment]
Hi Gavin,

Sorry for being slow to get back to you and thanks very much for flagging this. I have hopefully fixed it in the latest commit to the devel branch. 

I think it was caused by a large number of gene pairs having the same presence/absence pattern which caused an issue with the quantile filter that ignores those pairs with low MI values.

I'm planning to submit an updated version soon.
