### ISSUE TITLE
Gene in gene_presence_absence.Rtab not found in pan_genome_reference.fa

### ISSUE THREAD

**Issue by cthrnshn** [gtonkinhill/panaroo#137]
Hi,

I have been doing GWAS tool using the panaroo-generated gene_presence_absence.Rtab file as the input file. The GWAS tool will output the names of genes (based on the gene_presence_absence.Rtab input file) that have significant associations. Then, I look for the sequence of significant genes in pan_genome_reference.fa file. However, one of the significant hits did not have a sequence in the pan_genome_reference.fa. Do you know why this could be happening?

**Comment by gtonkinhill** [comment]
Hi,

Yes, this is usually when the hit is a paralog. Currently Panaroo only outputs a single version of each paralog to the `pan_genome_reference.fa` file. This is to prevent the reference from having duplicate genes which can cause issues with alignment.
