### ISSUE TITLE
alignments having both .fasta and aln.fas files

### ISSUE THREAD

**Issue by smb20200615** [gtonkinhill/panaroo#138]
I am comparing the aligned sequences in roary with those of panaroo and panaroo has a lot of files ending in .fasta in the aligned sequences folder. Is there a way that I can get the alignments in a similar format as roary?

Thank you,

**Comment by nzmacalasdair** [comment]
Hi @smb20200615 ! The alignments in the .aln.fas files should be in the same format as the alignments output by roary (FASTA formatted). Panaroo may, depending on which option flags are used, not delete intermediate files, in which case unaligned sequence files in FASTA format (.fasta files) will also be present in the output folder.
