### ISSUE TITLE
duplicate sequences in the final reference pangenome

### ISSUE THREAD

**Issue by shubavarshini** [gtonkinhill/panaroo#140]
Hello there,

I'm using Panaroo version 1.2.2 to create pangenomes of ~25 thousand species. Installed panaroo via conda in a new environment. During my analysis I came across pangenome reference sequences with 100% identity. Technically that should not be happening while creating pangenomes of a single species.  Enclosing the files after running Panaroo v1.2.2: https://drive.google.com/file/d/1-sEv_Ouctvm5e8Dre9IzzTc3StMWNm4h/view?usp=sharing
Prokka and Panaroo commands used:
run_prokka -t 24 -i ${path}/*.fna -o $path
panaroo -t 10 -i ${path}/*/*.gff -o ${path}/panaroo_results_default --clean-mode strict
Here's an elaborate example for species Bacteroides vulgatus. There were 24 GFF files generated using Prokka as per Panaroo's suggestion. The pangenome consists of ~11 thousand genes. The following pairs of reference gene sequences are identical to each other:
group_9154 and group_562
group_5681 and group_7117
group_9020 and group_6373
group_9152 and group_6355
group_5475 and group_6541 and group_6544
group_169 and group_9104 and group_9107
group_5578 and group_7490
group_9010 and group_6624

Considering only group_5681 and group_7117: I see that all the genes from individual strains were clustered together after CD-HIT
>Cluster 2508
0 521aa, >8_0_492... *
1 521aa, >8_0_1241... at 100.00%
2 521aa, >8_0_1338... at 100.00%
3 521aa, >13_9_526... at 98.66%
4 521aa, >13_16_154... at 99.04%
5 521aa, >16_11_106... at 98.85%
6 521aa, >16_21_7... at 98.85%
7 521aa, >16_32_24... at 98.85%
8 521aa, >18_1_81... at 99.04%
9 521aa, >21_8_54... at 100.00%
10 521aa, >21_32_89... at 100.00%
11 521aa, >21_33_104... at 100.00%

When I looked at the final graph that is used to group the genes: Enclosing screen shot.
![Screenshot from 2021-11-29 18-55-45](https://user-images.githubusercontent.com/47524561/144004938-599448c5-bdb1-4fff-8065-1cbe36253e1b.png)
 There is something that I do not understand. I do not know why the node for group_7117 includes genes from other clusters and then ends up choosing the same gene because of it's length to be the representative sequence. If you notice, in some of the genome annotations the centroids sequences is a hypothetical protein.
I do not understand why there are identical sequences in the final pangenome reference fasta. Please let me know if you can explain this behaviour since it is seen in all the ~25 thousand pangenomes I have created using panaroo.

**Comment by aweimann** [comment]
From your screen shot, I can tell that the paralog flag is set for these two gene families. So while they are identical, Panaroo inferred that they have a different genomic context. It's worth checking for the others clusters as well.

**Comment by aweimann** [comment]
Yes that's the idea. Unfortunately, there is no information in the Panaroo output that would allow you to link the paralogs. It's on the list of features to add to Panaroo. Thanks for expressing your interest in this.

As for your second query, for every read mapper this will be a challenging situation. If the paralogs are sufficiently similar, there is no way for the mapper to tell what is the right place for a read is. You might be able to increase the stringency of the mapping though depending on what tool you use. 

Good luck with your analysis.

Cheers, Aaron
