### ISSUE TITLE
subprocess Hangs. "os.waitpid(self.pid, wait_flags)"

### ISSUE THREAD

**Issue by WuyouGU** [gtonkinhill/panaroo#142]
I'm using Panaroo v1.2.9 under Python v3.9.5 for core genome analysis of 86 samples. 
Here is my command: 

> panaroo -i ./*.gff -o ../04_Prokka_core_genome --clean-mode strict -a core --core_threshold 0.95 -t 10

However, after the screen output "collapse mistranslations...", there are no outputs on the screen and no changes in the outdir anymore. 
I checked the process status, and the process was still running.

Then I stopped the process, here is the traceback:

> Traceback (most recent call last):
>   File "/data3/accout/ly/.conda/envs/pana2/bin/panaroo", line 10, in <module>
>     sys.exit(main())
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/site-packages/panaroo/__main__.py", line 332, in main
>     G = collapse_families(G,
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/site-packages/panaroo/clean_network.py", line 113, in collapse_families
>     cdhit_clusters = iterative_cdhit(G,
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/site-packages/panaroo/cdhit.py", line 411, in iterative_cdhit
>     run_cdhit_est(input_file=temp_input_file.name,
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/site-packages/panaroo/cdhit.py", line 147, in run_cdhit_est
>     subprocess.run(cmd, shell=True, check=True)
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/subprocess.py", line 507, in run
>     stdout, stderr = process.communicate(input, timeout=timeout)
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/subprocess.py", line 1126, in communicate
>     self.wait()
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/subprocess.py", line 1189, in wait
>     self.wait()
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/subprocess.py", line 1189, in wait
>     return self._wait(timeout=timeout)
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/subprocess.py", line 1917, in _wait
>     (pid, sts) = self._try_wait(0)
>   File "/data3/accout/ly/.conda/envs/pana2/lib/python3.9/subprocess.py", line 1875, in _try_wait
>     (pid, sts) = os.waitpid(self.pid, wait_flags)

I'm unsure how to solve this problem.

**Comment by WuyouGU** [comment]
I tried to run this command line again with only 5 samples and finally get the result after about 30-40min. I think I need to wait for a longer time. Therefore I closed the issue.

**Comment by gtonkinhill** [comment]
Hi,

It looks like its taking a long time to run cd-hit which is normally fairly quick. You might need to double check you have the multi-threaded version of cd-hit installed.

**Comment by WuyouGU** [comment]
Hi! Thanks for your reply. The cd-hit I installed is v4.8.1 and it runs with a CPU use of 2000%. Therefore, I think the version of cd-hit installed is correct. Then I checked the running command and it looks like this:

```
(base) [ly@localhost ~]$ cat /proc/`pgrep cd-hit`/cmdline
cd-hit-est-T20-i/data4/CLC_data4/liyue/03_PA0221/04_core_genome/01_gff_by_Prokka/04_Prokka_core_genome/tmp5_bc1j4q/tmprwn9weeyt0.99t0.98-o/data4/CLC_data4/liyue/03_PA0221/04_core_genome/01_gff_by_Prokka/04_Prokka_core_genome/tmp5_bc1j4q/tmprwn9weeyt0.99t0.98t0.95-c0.9-s0.0-aL0.0-AL99999999-aS99999999-AS99999999-r1-M0-d999-maskNX-n7
```

Is it right for the "-aS" parameter to be "99999999"? Looking forward to your reply.

**Comment by gtonkinhill** [comment]
Hi,

Yes, that is correct. I'm not sure why it is running slowly. We have run much larger datasets than that which have finished in under half an hour.

**Comment by WuyouGU** [comment]
Hi! Thanks for your kind and timely reply. Guess I just need to be patient and wait for the result :)
