### ISSUE TITLE
Order of core gene alignment

### ISSUE THREAD

**Issue by wtmatlock** [gtonkinhill/panaroo#146]
Hi,

When running Panaroo with the `a -core` flag, how is the order of genes in the resulting `core_gene_alignment.aln` determined?

Thanks,

Will

**Comment by gtonkinhill** [comment]
Hi Will,

The order of genes in the core genome alignment is not organised by Panaroo and might depend a bit on the operating system and how it sorts files by default. However, the genes in the `pan_genome_reference.fa` file are ordered based on their position in the graph. Depending upon how messy the graph is this can be more or less useful.

We could look at adding an order for the core genome alignment if there is a good use case for it. This would probably involve using the rough order suggested by the graph.

**Comment by dixienaik** [comment]
Hi,

I wanted to check if an order for the core genome alignment had been added, if not is there a way of using the gene alignments to do this? I'm currently trying to look at divergence across the core genome and so it would be useful to have a core genome in order even if it is a rough order. 

Thanks,
Dixie
