### ISSUE TITLE
What happens to non-protein coding annotations

### ISSUE THREAD

**Issue by shubavarshini** [gtonkinhill/panaroo#150]
Hi @gtonkinhill and others,

I have been using panaroo v1.2.9 but I had annotated the genomes using run_prokka.py from panaroo v1.2.2. I had two questions:
1. Does run_prokka.py differ between the two versions of panaroo?
2. Since the default run_prokka.py predicts coding and non-coding protein annotations, so while creating pangenomes does panaroo considers only the CDS sequences from the provided gff files and not other non-protein coding annotations like rRNA, tRNA or sRNA?

It would be helpful if you can clarify my doubts. Helps me understand the pangeomes.

**Comment by gtonkinhill** [comment]
Hi,

The `run_prokka.py` should be the same in both versions. As the latest version of Prokka has an option to specify the training model used by Prodigal the `run_prokka.py` script is redundant and we may remove it in future versions.

Panaroo only considers CDS sequences and will ignore r/t/sRNAs.

**Comment by shubavarshini** [comment]
Thanks for the quick response @gtonkinhill
