### ISSUE TITLE
Installation panaroo

### ISSUE THREAD

**Issue by H440775h** [gtonkinhill/panaroo#152]
I install panaroo using "mamba install -c conda-forge -c bioconda -c defaults panaroo
" but I [revived]
![panaroo](https://user-images.githubusercontent.com/99147495/161054866-0f1002b6-6ffa-4803-a694-131923550c5f.png)
 "panaroo: command not found"

**Comment by gtonkinhill** [comment]
Hi,

It looks like Panaroo was not successfully installed. Are you able to check that you have activated the correct conda environment?

**Comment by dhiru16** [comment]
the installation is failing both through conda and also through mamba.
<img width="1512" alt="Screen Shot 2022-04-01 at 5 26 08 PM" src="https://user-images.githubusercontent.com/96434814/161343571-3895b1bd-ed0c-4df5-a26f-cc4c1355a6ae.png">

**Comment by gtonkinhill** [comment]
Hi,

I am able to install using conda in a clean environment so I think this may be an issue with your conda installation/environment.

I would suggest trying in a clean environment using

```
conda create -n panaroo-env python=3
conda activate panaroo-env
conda install -c bioconda panaroo
```

**Comment by gtonkinhill** [comment]
It can take a while as conda struggles a bit to sort out the dependencies. An alternative would be to either install it manually or use a docker container https://quay.io/repository/biocontainers/panaroo?tab=tags
