### ISSUE TITLE
"xx_refound_yy" marked genes

### ISSUE THREAD

**Issue by mhjonathan** [gtonkinhill/panaroo#155]
Hi, 

I'm so excited to find this wonderful tool and working with it now, but I run into a trouble with "gene_presence_absence.csv" data.

I get a clean presence/absence data after using "panaroo-filter-pa -i ./gene_presence_absence.csv -o ./ --type pseudo,length,frag", and I wonder what "xx_refound_yy" queries mean. Does this mean the query sequence is also found in other part of genome of same sample so that it is needed to be removed manually? Or does this mean like, "Hey, your input data says this gene is on xx query, but we also find on yy query, too! It's identical each other so it was not filtered out through former panaroo-filter-pa command. It's up to you how to deal with it"?

**Comment by gtonkinhill** [comment]
Hi,

The "xx_refound_yy" represent genes that have been identified by Panaroo which were missing from the input GFF file. 
That is a gene sequence that was not annotated originally in this genome but where a very similar sequence has been annotated in another genome in the analysis.

The 'xx' represents the genome it was found in and the 'yy' is a count of all the re-found genes and is mainly used to distinguish them.

I hope this helps!

**Comment by mhjonathan** [comment]
Hey, thank you for your quick reply.

So, for instance, if my input data says Sample 1 contains gene A, gene B but Sample 2 only contains gene A, Panaroo detects gene B sequence on some location of Sample 2, and it marks as "1_refound_yy", right?

**Comment by gtonkinhill** [comment]
Yes, Panaroo only searches nearby sequence so in this scenario the re-found gene would likely be near gene A.

**Comment by mhjonathan** [comment]
Thank you for clear answer :) I don't have any more question on this issue, so I'll close it.

**Comment by iaposto** [comment]
Hi, if I may ask another question on this topic; how can one find the sequence of refound genes in the "gene_data.csv"?

**Comment by gtonkinhill** [comment]
These should be appended at the end of the file and will include the sequence name (i.e. "xx_refound_yy")

**Comment by iaposto** [comment]
Thank you!
