### ISSUE TITLE
Core genes are incorrectly selected

### ISSUE THREAD

**Issue by mhjonathan** [gtonkinhill/panaroo#157]
Hi,

I accidentally find out that there are some gene families in gene_presence_absence.csv which are classified as Core gene but not existing more than 95% (I set the core gene parameter as 0.95).

Most of genes are correct, but some genes exist in half or less than half of samples. This is the command I used for it:

panaroo -i ~/*.gff -o panaroo_outcome --clean-mode strict -a core --aligner mafft -t 20 -f 0.8 -c 0.95 --remove-invalid-genes

Version of the tool is 1.2.10

**Comment by mhjonathan** [comment]
Hi, thank you for your prompt reply!

I've tried again with same parameter (As you mentioned, I mistakenly said -c 0.95 parameter as core genome threshold.. I meant to say as you mentioned, the identity threshold.) with public Staphylococcus aureus whole sequence as I can't upload the data I used to open this issue, but I find same issue. I upload the gff files I used and they are from Prokka v.1.14.5 in command below:

`prokka --outdir ./aureus_xx --prefix yy --addgenes --rfam --cpus 30 ./query_sequence/aureus_yy.fna
`
[aureus_gffs.zip](https://github.com/gtonkinhill/panaroo/files/8561585/aureus_gffs.zip)

**Comment by gtonkinhill** [comment]
Hi,

I am having trouble reproducing the problem. After running Panaroo I got a summary stats file with

```
Core genes      (99% <= strains <= 100%)        2163
Soft core genes (95% <= strains < 99%)  0
Shell genes     (15% <= strains < 95%)  938
Cloud genes     (0% <= strains < 15%)   728
Total genes     (0% <= strains <= 100%) 3829
```

This matched the number of core genes in the `core_alignment_header.embl` file

```
grep -c "feature" core_alignment_header.embl
2163
```

and looking at one of the example genes you suggested indicated that it was a core gene

```
grep "entA_2~~~entA_1~~~entA" gene_presence_absence.csv
entA_2~~~entA_1~~~entA~~~entA_3,entA_2;entA_1;entA;entA_3,Enterotoxin type A,OOMFJBJJ_01682;OOMFJBJJ_01683,IAPLGABE_00528,KGKHIBFN_00210,NNHFGAFF_00587,AHBIBOMJ_00826;AHBIBOMJ_00827,NGMFOKNO_01152,GPNNNAAH_00523;GPNNNAAH_00522,DGPIMLGK_00309;DGPIMLGK_00310,NDEOMLED_00393,MKBCIDPL_00232;MKBCIDPL_00233,CKOIAKNC_00205;CKOIAKNC_00206,IMIKMCFN_00827;IMIKMCFN_00826,MPMBBJDA_01613;MPMBBJDA_01612,MPGAPHMD_00612;MPGAPHMD_00613,OONMPPGH_02431;OONMPPGH_02430,AJJGIOCN_00809;AJJGIOCN_00808
```
