### ISSUE TITLE
Panaroo and Gene Ontology

### ISSUE THREAD

**Issue by nicola-palmieri** [gtonkinhill/panaroo#161]
Dear Panaroo author, 

I am Dr Nicola Palmieri from the Veterinary University of Vienna (Austria). I have used Panaroo to compute the gene presence/absence matrix in a set of ~2000 E. coli avian strains and detected some candidate genes responsible for high pathogenicity in chicken using a GWAS approach.

Now I would like to do a standard GO enrichment analysis. My question is how to convert the gene IDs from Panaroo to gene IDs that are recognized by a Gene Ontology enrichment program such as Panther for example. I have tried to use the four-letter code (i.e. ompT) but some of the genes are not recognized by Panther or any other GO tool/web application.

Thank you.

Kind regards
Nicola

**Comment by gtonkinhill** [comment]
Hi Nicola,

We don't currently have a script to annotate genes with the names recognised by GO etc. This would probably be species and database specific so is not very easy to set up in a general way.

If you have a database of genes with corresponding GO terms it may be easiest to use a tool like BLAST to determine the corresponding GO annotations for each gene cluster.

**Comment by nicola-palmieri** [comment]
Thanks for the answer. I have thought so. To do candidate enrichment I have used as a background a set of genes from one strain (K-12) augmented with the rest of the candidates that were not present in that strains. I am not sure whether this is legal. I have never done GO enrichment for genes from a bacterial pan-genome. Should one use the whole pan-genome as a background?

Thanks!!
Nicola

**Comment by nzmacalasdair** [comment]
Hi Nicola,

I am not an expert in GO enrichment analyses, but I think comparing the pan-genome of some isolates of interest vs. the pan-genome of the rest of the isolates would make sense, so long as the sampling which makes up both groups of isolates is comparable.
