### ISSUE TITLE
merge pangenome graphs for different species

### ISSUE THREAD

**Issue by joglekarp** [gtonkinhill/panaroo#175]
Hi

I am interested in merging individual pan-genomes generated for three species (with distinct ANI) within a genus. Is there a recommendation about whether it is okay to split paralogs in order to run panaroo-merge successfully? 

Thanks

**Comment by joglekarp** [comment]
Hi,

Thank you. This is very helpful. Just to be sure that as a novice I understand this process, merge graph is based on gene synteny and not sequence identity? Also would the `--search_radius ` parameter be useful to resolve some of the "more diverse gene families" that you warn about? thx

**Comment by gtonkinhill** [comment]
Hi,

Not quite. It uses both synteny and sequence identity but very diverse genes that appear in very different locations in the two species may not be clustered together.

Adjusting the `--search_radius` might help a little bit but making it too large increases the chance that genes may be incorrectly clustered together. A better option might be to relax the initial clustering threshold using `--threshold` option. 

I would suggest running the merge using the default settings initially and then investigating the resulting graph in Cytoscape to see if it looks reasonable. You could then test how sensitive the results were to changes in the parameter settings.

**Comment by joglekarp** [comment]
Thank you.

**Comment by joglekarp** [comment]
Thank you
