### ISSUE TITLE
Ordering the core alignment

### ISSUE THREAD

**Issue by dixienaik** [gtonkinhill/panaroo#176]
#146 

Hi,

I wanted to check if ordering the core genome had been added? If not, is there a way to use any of the outputs to control how the gene alignments are ordered? I'm currently looks at divergence across the core genome and so an order core genome would be useful, even if it were a rough order.

Thanks,
Dixie

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the very slow reply. I missed this initially. 

We have not yet added any order for the core genome. The best approach currently would probably be to use the order information provided in the `final_graph.gml` file. The  `size` parameter on each edge gives an indication of how consistently two genes appear adjacent to each other within a pangenome.
