### ISSUE TITLE
panaroo with RAST output

### ISSUE THREAD

**Issue by snackens** [gtonkinhill/panaroo#178]
Hi, thank you for this useful tool.

Is it possible to use RAST annotation output file?

Best regards,

**Comment by gtonkinhill** [comment]
Hi,

I am currently looking into adding support for additional input types. I am afraid I have not used RAST before and so am unsure what format it outputs annotations in. Am I correct in thinking that it outputs GFF files in the same format as that provided by PATRIC?

**Comment by snackens** [comment]
Thank you for your reply. 
Yes, I performed annotation using PATRIC server. Actually, I probably conducted panaroo using RAST outputs susccessfly.
As previous Issues at roary page(#332), I added "##FASTA" and its sequence in the end of GFF from RAST. Additionally, I changed "Name=" to "product=" like GFF from prokka. Then I could obtain the results with RAST Annotation. The only thing that is different is GFF form RAST does not contain gene names.
Do you think panaroo have run well?

**Comment by gtonkinhill** [comment]
Hi,

I don't think you need to change 'Name' to 'product'. I have now updated Panaroo to include the ability to provide separate GFF and FASTA files. 

If you have the time it would be great if you were able to check this worked for you. The dev version can be installed by running

```
pip install git+https://github.com/gtonkinhill/panaroo@devel
```

The files need to be provided as a list in a text file with one isolate per line with the GFF and FASTA file separated by a space or tab. i.e

```
isolate_1.gff isolate_1.fasta
isolate_2.gff isolate_2.fasta
.
.
.
```

**Comment by snackens** [comment]
Thank you for your help.
I tried to run panaroo dev ver using following command, but I got error.

`panaroo -i list-panaroo-devel.txt -o result --clean-mode strict -a core --core_threshold 0.98 -t 16 -f 0.7 --remove-invalid-genes`

/bin/sh: cd-hit: command not found
Need cd-hit to be runnable through: cd-hit

**Comment by gtonkinhill** [comment]
This looks like it was an issue with the installation. I have now made a new release v1.3.0 which should be available on bioconda soon. Hopefully this helps with the installation.
