### ISSUE TITLE
What does the ~~ mean in the output presence/absence tables?

### ISSUE THREAD

**Issue by teddyaroca** [gtonkinhill/panaroo#185]
Hi,

I noticed that we see one or several ~ symbols in the gene names in the output tables and individual gene alignments. I was wondering what that means.

Thanks,

**Comment by gtonkinhill** [comment]
Hi,

If cluster includes multiple distinct gene names (taken from the input GFF files), Panaroo will separate them with `~~~`

**Comment by teddyaroca** [comment]
Thank you!

I was not aware of that. I appreciate your time.

**Comment by gtonkinhill** [comment]
No worries :)
