### ISSUE TITLE
tRNA genes not included in gene presence/absence

### ISSUE THREAD

**Issue by conmeehan** [gtonkinhill/panaroo#191]
Hi,

I am trying to compare a set of GFF files output from Bakta and it seems that any gene that is annotated as an RNA gene (e.g. tRNA or rRNA such as 16S) in the GFF file is not anywhere in the panaroo output files. Does Panaroo ignore non-protein coding gene entries? If so, which genes exactly are included in the gene presence/absence calculations? Is there a way to ensure all genes in the GFF are present in the panaroo outputs?

Thanks,
Conor

**Comment by gtonkinhill** [comment]
Hi Conor,

Yes, Panaroo only considers 'CDS' GFF entries. Unfortunately, there is not currently a way to include tRNA etc in the output but hopefully I will be able to add this feature in the future.

**Comment by gtonkinhill** [comment]
Yes, however we are hoping to add intergenic regions soon! 

Although it's common, I generally avoid using core genome alignments for downstream phylogenetics as the output can not be used with most recombination detection algorithms. We are hoping to add an improved core genome output in the next couple of weeks although this won't address the recombination issue yet.

**Comment by conmeehan** [comment]
Ok I follow. Since its on Mycobacterium tuberculosis, recombination detection is not an issue! We are trying to create sequencing baits from the pangenome but these would need to include the RNA-coding genes too, especially the core ones, so we just need to add them manually I guess. If you do find a way to include non-CDS genes into pangenome, please let us know!

C
