### ISSUE TITLE
easy way to extract core_genome_reference.fa, soft_genome_reference.fa and etc ...

### ISSUE THREAD

**Issue by amvarani** [gtonkinhill/panaroo#193]
Hi there,

Just a simple question.
Is there a simple way to extract a reference fasta file of each Core, Soft core, Shell, and Clound genes ? 
In another word, split the pan_genome_reference.fa into these different sets ? 

Best

**Comment by gtonkinhill** [comment]
Hi,

I am afraid there is not script to do this at the moment. It is probably easiest to achieve this by pulling representative sequences from the `gene_data.csv` file. You can use the `gene_presence_absence.csv` file to work out which class each gene is in.

**Comment by amvarani** [comment]
Thanks!
I got the representative fastas playing with the gene_data.csv and the gene_presence_absence.csv file.
