### ISSUE TITLE
How to remove any strains from panaroo results without rerunning it?

### ISSUE THREAD

**Issue by YiweiZhu** [gtonkinhill/panaroo#199]
Hi, I have learned how to [add single genome](https://gtonkinhill.github.io/panaroo/#/merge/add_single). In some cases, some strains are involved by mistake. Is it possible to remove any strains from the results or add/remove simutaneously without rerunning the program?

**Comment by gtonkinhill** [comment]
Hi,

I'm afraid not. Although it would be possible to write a function to do this, it would be tricky to make sure that it gave the same result as if the excluded genome had never been included in the first place.

**Comment by YiweiZhu** [comment]
Thanks for your reply!
