### ISSUE TITLE
Panaroo not reading my gff files

### ISSUE THREAD

**Issue by jaoanjos** [gtonkinhill/panaroo#200]
Hello how are you? I'm trying to use panaroo, but it can't read my gff files, I don't know, do I need to create or move the gff file to a specific folder before using the program?
I did just by this test line:
panaroo -i *.gff -o results --clean-mode strict

result:
Traceback (most recent call last):
  File "/home/joao/anaconda3/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/joao/anaconda3/lib/python3.9/site-packages/panaroo/__main__.py", line 288, in main
    files.append(create_temp_gff3(line[0], line[1], temp_dir))
  File "/home/joao/anaconda3/lib/python3.9/site-packages/panaroo/prokka.py", line 88, in create_temp_gff3
    with open(gff_file, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '##gff-version'

Thank you very much and a big hug!

**Comment by gtonkinhill** [comment]
Hi,

You need to provide the path to the gff files. The command you ran should work if it is running the in the same directory as the gff files are located.

**Comment by gtonkinhill** [comment]
Hi,

Panaroo was initially written to take the output of Prokka rather than NCBI files. However, we have recently added this functionality but the input file paths must be provided as a list in a text file rather than on the command line. There is more information about this in the docs [here](https://gtonkinhill.github.io/panaroo/#/gettingstarted/quickstart?id=different-input-formats)

**Comment by Oelsakha** [comment]
hi all 
I have the same problem and my gff file is resulted from PROKKA. and i am sure that the file path is correct. 

can anyone help me

**Comment by gtonkinhill** [comment]
Hi,

Could you copy the output you are receiving? If possible it would be helpful if you could also provide a small reproducible example. This would help me a lot in working out what is causing the issue.

**Comment by Oelsakha** [comment]
panaroo -i PROKKA_10132022/PROKKA_10132022.gff -o results --clean-mode strict


Traceback (most recent call last):
  File "/Users/mo/miniconda3/bin/panaroo", line 33, in <module>
    sys.exit(load_entry_point('panaroo==1.3.0', 'console_scripts', 'panaroo')())
  File "/Users/mo/.local/lib/python3.9/site-packages/panaroo-1.3.0-py3.9.egg/panaroo/__main__.py", line 288, in main
  File "/Users/mo/.local/lib/python3.9/site-packages/panaroo-1.3.0-py3.9.egg/panaroo/prokka.py", line 88, in create_temp_gff3
FileNotFoundError: [Errno 2] No such file or directory: '##gff-version'

**Comment by gtonkinhill** [comment]
Hi,

Panaroo requires at least two but preferably more gff files to run. As you provide only a single file it is defaulting to assuming you are providing a text file with path names.
