### ISSUE TITLE
Panaroo version in bioconda is 1.1.2 

### ISSUE THREAD

**Issue by naturepoker** [gtonkinhill/panaroo#202]
Hi, 

I actually left a quick message on a previously closed issue about Biopython alphabet issue - 

When installing panaroo from bioconda repo (as of Oct 12th 2022), the installation defaults to version 1.1.2, resulting in the Biopython alphabet deprecation error again. 

Forcing the most current version via:

```
mamba install -c bioconda panaroo==1.3.0
```

Results in error message:

```
 - package panaroo-1.3.0-pyhdfd78af_0 requires biocode, but none of the providers can be installed
```

Running down the list of required packages one at time eventually asks for mkl, after which error message loops (even after installing mkl)

```
- package panaroo-1.3.0-pyhdfd78af_0 requires mkl, but none of the providers can be installed
```

I think panaroo installation via conda simply isn't working at this time. 

Let me know if you need more info from my end. 

Thank you!

**Comment by gtonkinhill** [comment]
Closing this as I've reopened the old issue.
