### ISSUE TITLE
core genome

### ISSUE THREAD

**Issue by luhan125** [gtonkinhill/panaroo#203]
Hi,

Panaroo is really good tool for analysing the pangenome, it works well in my server. 
I have a question, how can I find core genes in output files of Panaroo?
Looking forward to your reply.

Thank you a lot!

**Comment by gtonkinhill** [comment]
Hi,

The best way to do this would be to look at the `gene_presence_absence.Rtab` file. I typically load this into R to determine the conservation of each gene. Alternatively you could use python or excel.

**Comment by luhan125** [comment]
Hi,

Thank you very much for your reply. Now, I have a new question. Panaroo has ran more than 35 hours, and still not end. The number of gff files is 200, so this situation is normal? Now, nohup.out is:

running cmd: cd-hit -T 1 -i /home/liuzh/drug_resistance/cgMLST/test/panaroo/result/combined_protein_CDS.fasta -o /home/liuzh/drug_resistance/cgMLST/test/panaroo/result/combined_protein_cdhit_out.txt -c 0.98 -s 0.98 -aL 0.0 -AL 99999999 -aS 0.0 -AS 99999999 -M 0 -d 999 -g 1 -n 2
generating initial network...
Processing paralogs...
100%|██████████| 8879/8879

Thank you a lot!

**Comment by gtonkinhill** [comment]
Hi, it looks like you are running panaroo with a single core. I would recommend increasing the number of cpu's using the `-t` option.

**Comment by luhan125** [comment]
I tried to invrease cores, it worked well. I just confused the results of summary_statistics.txt, what do these (Soft core genes, Shell genes,Cloud genes)mean? What's the threshold of gene numbers?

 

Core genes      (99% <= strains <= 100%)        125
Soft core genes (95% <= strains < 99%)  2126
Shell genes     (15% <= strains < 95%)  6120
Cloud genes     (0% <= strains < 15%)   30699
Total genes     (0% <= strains <= 100%) 39070



Thank you a lot！










在 2022-10-20 07:34:35，"Gerry Tonkin-Hill" ***@***.***> 写道：

Hi, it looks like you are running panaroo with a single core. I would recommend increasing the number of cpu's using the -t option.

**Comment by luhan125** [comment]
Hi,

In gene_presence_absence.Rtab file. The form of one core gene are guaA_4~~~guaA_3~~~guaA_1~~~guaA_2~~~guaA~~~guaA_6~~~guaA_5, what do these mean? When I searched one (like guaA_4), several guaA_4 can be found in gene_presence_absence.Rtab file. So, how can I make sure the core genes?

Thank you!

This is the form of gene_presence_absence.Rtab file:
Gene	Ab100	Ab101	Ab102	Ab103	Ab104	Ab105	Ab106	Ab107	Ab108
guaA_4~~~guaA_3~~~guaA_1~~~guaA_2~~~guaA~~~guaA_6~~~guaA_5	1	1	1	1	1	1	1	1	1
soj_2~~~soj_1~~~parA_2~~~parA_3~~~parA~~~parA_1~~~parA_4	1	1	1	1	1	1	1	1	1
