### ISSUE TITLE
the form of core genes in gene_presence_absence.Rtab

### ISSUE THREAD

**Issue by luhan125** [gtonkinhill/panaroo#205]
Hi,

In gene_presence_absence.Rtab file. The form of one core gene is : guaA_4~~~guaA_3~~~guaA_1~~~guaA_2~~~guaA~~~guaA_6~~~guaA_5, what do these mean? When I searched one (like guaA_4), several guaA_4 can be found in gene_presence_absence.Rtab file. So, how can I make sure the core genes?
 
I am looking forward to your reply!

Thank you!

This is the form of gene_presence_absence.Rtab file:
Gene	Ab100	Ab101	Ab102	Ab103	Ab104	Ab105	Ab106	Ab107	Ab108
guaA_4~~~guaA_3~~~guaA_1~~~guaA_2~~~guaA~~~guaA_6~~~guaA_5	1	1	1	1	1	1	1	1	1
soj_2~~~soj_1~~~parA_2~~~parA_3~~~parA~~~parA_1~~~parA_4	1	1	1	1	1	1	1	1	1

**Comment by gtonkinhill** [comment]
Hi @luhan125 ,

From your earlier post it looks like you are running Panaroo on metagenomic data. It was not designed for this so if that is the case I would recommend using a different tool.

The gene names in panaroo include all gene names in each cluster separated by a `~~~`. 

Please refrain from posting questions on other users issues as this creates confusion. 

I am afraid I am unable to answer so many questions about how to interpret the output of pangenome software. I will do my best but it might be better to read the documentation and some background material carefully before posting additional questions.
