### ISSUE TITLE
Question about multithreading during paralog phase

### ISSUE THREAD

**Issue by rbeiko** [gtonkinhill/panaroo#207]
Hi, I'm currently running Panaroo on ~13,000 _Enterococcus_ genomes on an HPC cluster with the '-t 24' flag. The CD-HIT phase took about a day and the "Processing paralogs" step has been running for just over 40 hours, with an ETC ranging between 13h and 205h. I checked with the sysadmins and the process is currently using only 1 CPU.

Is Panaroo able to use multiple threads during the paralog phase? If not, are there any heuristics I might use at the frontend to speed things up? Many of the genomes are very similar so a pre-clustering would reduce the number of genes substantially, but I assume that this would be redundant with the CD-HIT phase of execution.

Thanks
Rob

**Comment by rbeiko** [comment]
Oops, sorry my search-fu failed - I see that this is basically #126. Any suggestions for heuristics pre-Panaroo would be welcome though!

**Comment by gtonkinhill** [comment]
Hi Rob,

For datasets this large I usually recommend running Panaroo iteratively. That is, running Panaroo on subsets of related genomes before merging the resulting graphs. Some documentation on how to do this is [here](https://gtonkinhill.github.io/panaroo/#/merge/merge_graphs).

I often use either PopPunk or fastbaps to do the intial clustering but the approach should be fairly robust to the clustering method. I usually aim for clusters of around 1000 genomes.

**Comment by rbeiko** [comment]
Thank you! I'll give that a try.
