### ISSUE TITLE
Question: What are the parameters in IMG output?

### ISSUE THREAD

**Issue by martinastoycheva** [gtonkinhill/panaroo#208]
Hello, 

I wanted to use the IMG helper script you provide for estimating the size of the pangenome to avoid the common errors assosiated with simply plotting a rarefaction curve. However, I am not familiar with this type of models and the paper you cite for it seems rather complicated and mathsy so I was wondering if you could give a brief explanation of the parameters that the model estmates. I assume ess is the estikate for the core genome size but what do v1, v2 and u1 mean?

<img width="383" alt="Screenshot 2022-10-28 at 14 44 22" src="https://user-images.githubusercontent.com/38460574/198620903-441c0f0e-3ed0-4a33-98b2-d3468f0d7795.png">

Thanks very much!
Martina

**Comment by gtonkinhill** [comment]
Hi,

I have found that this version of the IMG model does not perform particularly well and would now recommend the panstripe method available [here](https://github.com/gtonkinhill/panstripe).

If you are keen to use the IMG model the implementation in [panicmage](https://github.com/fbaumdicker/panicmage) tends to outperform that of Collins et al.
