### ISSUE TITLE
Meaning of multiple prokka IDs in a cell in presence/absence.csv?

### ISSUE THREAD

**Issue by aswing2364** [gtonkinhill/panaroo#209]
Hi! I noticed that in my presence_absence.csv there are times where for one isolate/one gene there will be multiple prokka IDs listed. I looked back through Panaroo resources, and I can't find anywhere that explicitly defines if these are supposed to represent fragmented genes (i.e., these two prokka IDs make up one gene) or something else (e.g. tandem duplications). Could you please clarify? Thank you!

**Comment by gtonkinhill** [comment]
Hi,

I am in the process of updating the docs which are admittedly fairly sparse. Multiple IDs represent fragmented genes as you have guessed. Hopefully this helps!
