### ISSUE TITLE
Unmatched aligned gene location on gff and panaroo graph

### ISSUE THREAD

**Issue by mhjonathan** [gtonkinhill/panaroo#211]
Hi,

I hope everything is going well!

I'm using Panaroo v1.3.0 to draw graph through Cytoscape, and I found interesting neighbouring genes on it. To figure out what else nearby them in each sample, I extract contigs containing those genes from individual samples, but they are not neighbouring according to gff files (even they are on the different contigs).

I thought it's possible not to have perfectly same figure, but it is too different to ignore on this case. 

Can you explain why this is happend?

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the slow reply. I am not sure I understand correctly, but for genes to be neighbours in the graph they only need to be neighbours in a single GFF file and thus might not be neighbouring in all GFF files in which they appear.

If you are able to send me a small example I am happy to take a closer look.

**Comment by mhjonathan** [comment]
Hi,

Thank you for the reply. 

I understand your answer, and then is there any option I can adjust that? Like, make genes being neighbours if there are at least 2 or 3 GFF files, not just one, showing neighbourhood?

**Comment by gtonkinhill** [comment]
Hi,

Yes, this is most easily done in Cytoscape which should allow you to interactively filter edges. The 'size' parameter for an edge indicates how many GFF files those genes appeared adjacent in. There is a rough guide on how to do this in the filtering section of the [documentation](https://gtonkinhill.github.io/panaroo/#/vis/cytoscape)

**Comment by mhjonathan** [comment]
Perfect!

Thank you for your kind replies. I'll close the issue with this comment.
