### ISSUE TITLE
Error while collapsing gene families

### ISSUE THREAD

**Issue by AmayAgrawal** [gtonkinhill/panaroo#215]
Hi,
I am using panaroo with default parameters to perform the pan-genome analysis and the program stops with the following error while collapsing the gene families:

> collapse gene families...
> Traceback (most recent call last):
>   File "/home/aag21/anaconda3/envs/panaroo_old/bin/panaroo", line 10, in <module>
>     sys.exit(main())
>   File "/home/aag21/anaconda3/envs/panaroo_old/lib/python3.10/site-packages/panaroo/__main__.py", line 358, in main
>     G, distances_bwtn_centroids, centroid_to_index = collapse_families(
>   File "/home/aag21/anaconda3/envs/panaroo_old/lib/python3.10/site-packages/panaroo/clean_network.py", line 141, in collapse_families
>     seqid_to_index[sid] = centroid_to_index[seqid_to_centroid[sid]]
> KeyError: '0_10_264'

I tried running it using both versions (1.3.2 and 1.3.0) and both results in same error. I also faced similar issues when I tried to run pan-genome analysis using other data as well. Can you please help me with this?

**Comment by gtonkinhill** [comment]
Hi,

Could you share a small reproducible example? This would help me a lot in working out what is causing the issue.

**Comment by AlperYurtseven** [comment]
Hi @gtonkinhill, I am facing same issue that is mentioned here. What was the solution that is applied to solve it? I am currently using version 1.3.4 and facing same issue.

**Comment by gtonkinhill** [comment]
Hi,

Please update to the latest version panaroo (1.4.2). This should hopefully fix this issue.

**Comment by AlperYurtseven** [comment]
Hi,
Thanks, version 1.4.2 is working fine with higher thread numbers
