### ISSUE TITLE
How to plot a simple pangenome accumulation curve (numb genes vs numb genomes) using the output of panaroo?

### ISSUE THREAD

**Issue by Liuyuxinn** [gtonkinhill/panaroo#216]
Hello.

How to plot a simple pangenome accumulation curve (numb genes vs numb genomes) similar to those produced by create_pan_genome_plots.R in rorary using the output of panaroo?

When I open this script (post-plot-runner.py),it showed:
#!/usr/bin/env python
"""Wrapper for running plotting functions directly from source tree."""

from panaroo.generate_abundance_plots import main

if __name__ == '__main__':
    main()

Would you have any hints for what could be going on?

Many thanks

**Comment by gtonkinhill** [comment]
Hi,

I generally recommend against using pangenome accumulation curves as they can be significantly biased by sampling bias as well as errors in gene annotation and clustering.

To avoid this we came up with a new regression based method [panstripe](https://github.com/gtonkinhill/panstripe). If you are really keen on an accumulation curve the panstripe R package also includes a function to create them.

If you're interested in how the approach works and the issues with accumulation curves we provide more detail in the [paper](https://genome.cshlp.org/content/early/2023/01/20/gr.277340.122)

**Comment by Liuyuxinn** [comment]
Hello,

I want to create an accumulation curve with the panstripe R package, however,one of input in panstripe is a phylogeny files.

How to build core genome phylogenies using panaroo’s output file?

Many thanks

**Comment by gtonkinhill** [comment]
If you are just interested in the accumulation curve you do not need a phylogeny, see [here](https://github.com/gtonkinhill/panstripe/#accumulation-curves). 

To build a core genome phylogeny you can run panaroo with using the `-a` flag. I would recommend building the phylogeny with the resulting `core_gene_alignment_filtered.aln` file using a tool such as iqtree
