### ISSUE TITLE
Trouble with Panaroo output

### ISSUE THREAD

**Issue by iagosblancos** [gtonkinhill/panaroo#218]
Hello everybody, I have installed Panaroo through **conda**, with all of its dependencies. Previously, my input _.gff_ files have been prepared with Prokka from _.fasta_. 
The program was supposed to generate as output these files: _gene_presence_absence.csv, gene_presence_absence.Rtab, final_graph.gml, struct_presence_absence.csv, pan_genome_reference.fa , gene_data.csv, combined_DNA_CDS.fasta, combined_protein_CDS.fasta, core_gene_alignment.aln, core_gene_alignment_filtered.aln_.
However, what I got as results was a folder with files:  "_combined_DNA_CDS.fasta", "combined_protein_cdhit_out.txt", "combined_protein_cdhit_out.txt.clstr", "combined_protein_CDS.fasta", "gene_data.csv_" and _"pre_filt.graph.gml"_. When trying to open this last one with Graphia or Cytoscape, the software indicated that the file was broken... Hence, in this results folder, a new temporary folder was created, titled "tmpmuglpxm8". 

Among the final messages shown after running Panaroo, I could see:
 ```
`312300  finished     292125  clusters

Approximated maximum memory consumption: 454M
writing new database
writing clustering information
program completed !
Total CPU time 2960.19
generating initial network...
Processing paralogs...
100%|████████████████████████████████████████████████| 476/476 [00:00<00:00, 1040.20it/s]
collapse mistranslations...
Traceback (most recent call last):
  File "/home/iago/.local/bin/panaroo", line 33, in <module>
    sys.exit(load_entry_point('panaroo==1.3.2', 'console_scripts', 'panaroo')())
  File "/home/iago/.local/lib/python3.8/site-packages/panaroo-1.3.2-py3.8.egg/panaroo/__main__.py", line 358, in main
  File "/home/iago/.local/lib/python3.8/site-packages/panaroo-1.3.2-py3.8.egg/panaroo/clean_network.py", line 113, in collapse_families
  File "/home/iago/.local/lib/python3.8/site-packages/panaroo-1.3.2-py3.8.egg/panaroo/cdhit.py", line 411, in iterative_cdhit
  File "/home/iago/.local/lib/python3.8/site-packages/panaroo-1.3.2-py3.8.egg/panaroo/cdhit.py", line 147, in run_cdhit_est
  File "/home/iago/miniconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd-hit-est -T 18 -i /home/iago/PiBAC assemblies/ncbi-genomes-2022-11-22/gff/agoravai/tmppdvcxppn/tmpxm2idyev -o /home/iago/PiBAC assemblies/ncbi-genomes-2022-11-22/gff/agoravai/tmppdvcxppn/tmp2vbb6k2l -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7 > /dev/null' returned non-zero exit status 1.`

```
I don't know what may be the problem, I have checked and updated all dependencies just recently

**Comment by gtonkinhill** [comment]
I have responded to the previous issue you commented on so I will close this one for now.
