### ISSUE TITLE
panaroo-extract-gene

### ISSUE THREAD

**Issue by hayleyjaywilson** [gtonkinhill/panaroo#219]
Hi. I am using the panaroo-extract-gene script to try and pull out some genes of interest but the various outputs are confusing me!
`panaroo-extract-gene --pa gene_presence_absence.csv --gene gene_data.csv -o gene_alignments -q group_1642 --dna` for example

The resulting output file for group_1642 has 300,000 sequences and of the few I have popped through Blast they are different?

Additionally if I take one of the headers of the representatives in the output fasta file from panaroo-extract-gene (which has been found via the gene_data.csv file) and search for it in gene_presence_absence.csv it leads to a different gene name in column A

The task I would like to achieve is to pull out specific sequences/groups that are currently labelled as hypothetical proteins and use blast to get a better understanding of what they are. I hope that all makes sense.

**Comment by gtonkinhill** [comment]
Hi Hayley,

Sorry for the slow response. This script was originally tested with Prokka output which generally produces different gene ids for each genome. However, this is not always the case and the script was not robust to duplicate gene IDs appearing in separate genomes.

I've hopefully fixed this bug in the latest version in the `devel` branch. I will create a new release soon but in the meantime the fix should be available by reinstalling using

```
pip install git+https://github.com/gtonkinhill/panaroo@devel
```
