### ISSUE TITLE
Conda build outdated (Bio.Alphabet issue)

### ISSUE THREAD

**Issue by RiescoR** [gtonkinhill/panaroo#224]
Hi, 
I just wanted to let you know that the conda install made by the suggested command
conda install -c conda-forge -c bioconda -c defaults panaroo 
is outdated and crashes at start with the error "Bio.Alphabet has been removed from Biopython"
I traced the error to the generate_output.py file, but given it has been solved in the master build in github, I guess you already knew. Also some of the main options like --clean-mode strict are changed to --mode strict. 
Should I reinstall with the github version? Or all should run ok if the generate_output.py is corrected?
Thanks!

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the slow reply. It looks like you might have a version issue as the parameter `--clean-mode` was changes quite a long time ago.

I would recommend installing Panaroo in a fresh conda environment with

```
conda create -n panaroo python=3.9
conda activate panaroo
conda install -c bioconda panaroo
```

I hope this helps!

**Comment by microbemarsh** [comment]
I'm having this same issue and I'm running into some errors with the install mentioned above. When running the last line,  the error message below pops up. I'm assuming I'm installing v1.3.3, which seems to have just been updated on the bioconda channel so not sure what is going on, I am using a SLURM HPC system and I would not have sudo access for installations.

`Could not solve for environment specs
Encountered problems while solving:
  - package panaroo-1.0.0-py_0 requires gffutils, but none of the providers can be installed

The environment can't be solved, aborting the operation`

**Comment by RiescoR** [comment]
Hi! sorry for the late answer too. Yeah, it was a version issue, I created a conda environment just for Panaroo, so it was not a big issue. For some reason the command for default installation suggested in the manual (conda install -c conda-forge -c bioconda -c defaults panaroo) installs the old version of the program. 
However, I could solve it updating with 
```
conda update panaroo
```
It works perfectly now
