### ISSUE TITLE
family threshold parameter and different proteins

### ISSUE THREAD

**Issue by nikolomics** [gtonkinhill/panaroo#225]
Hello,

We are working with a set of 300 bacterial genomes of specific species. We want to define a core set that we can use to describe these species. So it is important for the definition to be as accurate as possible. 
We have observed that using the default parameters including family threshold at 70% we get many different proteins clustered with the same gene. The proteins do not match.  For example :  
IPKJEAGK_00973	MAMVQPKSQKLRLFTTHLLLLIFIAAIMFPLLMVIAISLREGNFATGSLIPDTISWEHWRLALGFSVEHADGRVTPPPFPVLLWLWNSIKVAGITAIGIVALSTTCAYAFARMRFPGKATLLKGMLIFQMFPAVLSLVALYALFDRLGQYIPFVGLNTHGGVIFAYMGGIALHVWTIKGYFETIDGSLEEAAALDGATPWQGCCRCRCRFWQSCLFCRSSRPSPKCRSPRCCCAM

IPKJEAGK_00974	
VPVASLLLRDVNSYTLAVGMQQYLNPQNYLWGDFAAAAVLSAIPITVVFLLAQRWLVNGLTAGGVKG

The proteins above are clustered under the same gene.
Additionally, we did some more analysis with 95% instead of 70% family threshold:

Gene class	Family threshold = default	/ Family threshold = 0.95
			Gene count		Gene count
Core genes		2961		2890
Soft core genes	282			288
Shell genes		2528		2358
Cloud genes		19309		29617
Total genes		25080		35153

My question will be why so many differences all along the analysis considering the different parameters. What does it mean the two different proteins are clustered in the same family (is it due to fragmentation or missing parts as documentation mentions)? Does the 95% threshold in the protein level make sense? Which core gene dataset will be accurate?

Thank you so much and sorry for the so many questions.

Best regards,
Nikolas

**Comment by gtonkinhill** [comment]
Hi Nikolas,

These genes have probably been clustered at the DNA level which would indicate that the annotations are in different reading frames in each genome. 

To check this, you could pull out the DNA sequences using the `panaroo-extract-gene` command and align them using MAFFT with the `--adjustdirection` option enabled.

The family threshold indicates how diverse a gene (or cluster) is allowed to be. We have found 70% to be reasonable in most situations. 95% seems a bit high and will probably result in a lot of genes being split across multiple clusters.

I hope this helps!

**Comment by nikolomics** [comment]
Hello Gerry,

Thank you so much for the prone answer! Yes, I agree with you and think we will maintain the default parameter. The comparison indeed indicates that we lose 20-30 genes when the parameter changes. We will perform the alignment to be sure but for now we are ok!
