### ISSUE TITLE
Bio.Alphabet module has been removed from Biopython error

### ISSUE THREAD

**Issue by haochh** [gtonkinhill/panaroo#226]
Hi, 

After the installation, I encountered the below errors, can I ask if you have any idea to resolve it? Thanks very much! 

`Traceback (most recent call last):
  File "/drives/4tb/Chunhui/Environments/Panaroo_env/bin/panaroo", line 6, in <module>
    from panaroo.__main__ import main
  File "/drives/4tb/Chunhui/Environments/Panaroo_env/lib/python3.7/site-packages/panaroo/__main__.py", line 14, in <module>
    from .generate_output import *
  File "/drives/4tb/Chunhui/Environments/Panaroo_env/lib/python3.7/site-packages/panaroo/generate_output.py", line 10, in <module>
    from Bio.Alphabet import generic_dna
  File "/drives/4tb/Chunhui/Environments/Panaroo_env/lib/python3.7/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.`

**Comment by gtonkinhill** [comment]
Hi,

This is most likely a version issue. I would recommend installing Panaroo in a fresh conda environment by running

```
conda create -n panaroo python=3.9
conda activate panaroo

conda install -c bioconda panaroo
```

**Comment by haochh** [comment]
I forgot to say that I successfully installed it using python=3.9 and mamba solver. Thanks very much!

**Comment by gtonkinhill** [comment]
Thanks very much for letting me know. We've had a few other people run into issues with the most recent versions of python and are working on getting this fixed.
