### ISSUE TITLE
GFF3 from GenBank

### ISSUE THREAD

**Issue by canarioviana** [gtonkinhill/panaroo#227]
What is the correct method to generate a gff3 file from GenGank RefSeq database that is compatible with Panaroo? Gff3 files from GenBank have no fasta included. I used bp_genbank2gff3 to convert gbff files from GenBank to gff and got the error below from Panaroo.

Total CPU time 0.08
generating initial network...
Processing paralogs...
Traceback (most recent call last):
  File "/usr/local/bin/panaroo", line 33, in <module>
    sys.exit(load_entry_point('panaroo==1.3.3', 'console_scripts', 'panaroo')())
  File "/usr/local/lib/python3.10/dist-packages/panaroo-1.3.3-py3.10.egg/panaroo/__main__.py", line 338, in main
  File "/usr/local/lib/python3.10/dist-packages/panaroo-1.3.3-py3.10.egg/panaroo/clean_network.py", line 338, in collapse_paralogs
ValueError: max() arg is an empty sequence

**Comment by gtonkinhill** [comment]
Hi,

It is possible to pass separate GFF3 and FASTA files to panaroo by providing the paths to files in a tab separated list as described [here](https://gtonkinhill.github.io/panaroo/#/gettingstarted/quickstart?id=different-input-formats). 

For example you can create a list in a text file called `input_files.txt` formatted as

```
/path/to/genome_1.gff  /path/to/genome_1.fasta
/path/to/genome_2.gff  /path/to/genome_2.fasta
/path/to/genome_3.gff  /path/to/genome_3.fasta
```

Panaroo can then be run as

```
panaroo -i input_files.txt -o panaroo_output --clean-mode strict
```
