### ISSUE TITLE
Genes present in prokka gff files but present as group_xxx in gene_presence_absence_file 

### ISSUE THREAD

**Issue by simrangambhir** [gtonkinhill/panaroo#228]
Hi,
I have annotated a number of  bacterial genomes with Prokka, which contain the respective genes in the gff files. However, after pangenome construction done with Panaroo at default threshold, the same genes are present as group_xxx in the gene_presence_absence file generated by Panaroo. It will be great if we could find a way to prevent this.
Thanks
Simran

**Comment by gtonkinhill** [comment]
Hi,

Do you mean that you wish the group_xxx was replaced with the gene name? Panaroo currently labels clusters as 'group' if the same gene name is duplicated in multiple different clusters. This is the approach that Roary takes.

**Comment by simrangambhir** [comment]
Thank you for your response!
