### ISSUE TITLE
Errno2  No such file or directory: '##gff-version'

### ISSUE THREAD

**Issue by li-fangyeo** [gtonkinhill/panaroo#230]
Hi Gerry,

Thanks for developing Panaroo! (And naming it panaroo). 

I generated the gff file on prokka but I'm not sure what this error means. I even tried putting in the whole file address but it didn't work. What am I doing wrong? Help =) 

(panaroo) lilifanggi@DESKTOP-IJUVMDT:/mnt/c/Users/Li-Fang/Genetics/JehaiEcoli/Mappedreads/prokkaa$ panaroo -i JHEC01/JHEC01.gff -o panaroo/ --clean-mode strict
Traceback (most recent call last):
  File "/home/lilifanggi/anaconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/lilifanggi/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 302, in main
    files.append(create_temp_gff3(line[0], line[1], temp_dir))
  File "/home/lilifanggi/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 88, in create_temp_gff3
    with open(gff_file, 'r') as infile:
**FileNotFoundError: [Errno 2] No such file or directory: '##gff-version'**
(panaroo) lilifanggi@DESKTOP-IJUVMDT:/mnt/c/Users/Li-Fang/Genetics/JehaiEcoli/Mappedreads/prokkaa$ head -n 5 JHEC01/JHEC01.gff
##gff-version 3
##sequence-region NZ_JAGWDO010000001.1 1 3190775
##sequence-region NZ_JAGWDO010000011.1 1 5010
##sequence-region NZ_JAGWDO010000012.1 1 5264
##sequence-region NZ_JAGWDO010000013.1 1 3543

**Comment by gtonkinhill** [comment]
Hi,

Panaroo requires multiple (preferably at least 3) GFF files. 

When you provide a single file it assumes that you have provided a list of file locations which is why it is throwing this error.

**Comment by li-fangyeo** [comment]
Right!! Got it. Thank you!
