### ISSUE TITLE
Incomplete Panaroo output

### ISSUE THREAD

**Issue by asalahmadi2023** [gtonkinhill/panaroo#232]
Hi 

I ran Panaroo script as  -i /input_panaroo/*.gff -o Panaroo_results --clean-mode strict 
but after a short time it was finished and the results I got were incomplete compared to the output description on your page. Here is the screenshot of what I got from the run. 

![Screenshot 2023-05-26 004022](https://github.com/gtonkinhill/panaroo/assets/134656239/210e5bf5-f0ab-431e-8746-de3e1361fceb)

Why couldn't I get the other files like gene_presence_absence.csv or final graph.gml, ...

**Comment by gtonkinhill** [comment]
Hi,

It looks like Panaroo has crashed or has been forced to exit early. You would need to look at the output and check if an error has been thrown.
