### ISSUE TITLE
Warning or error?

### ISSUE THREAD

**Issue by raghuramdr** [gtonkinhill/panaroo#240]
Hi, I am using Panaroo to build the pangenome for a few thousand _K.pneunominiae_ genomes. I noticed this ambiguous message popping up early into the run, and was curious what it means or refers to
`Your word length is 2, using 5 may be faster!`

What exactly is the word length that the message is referring to?

**Comment by gtonkinhill** [comment]
Hi,

This message is generated by CD-HIT. The word length determines how short the kmers are that CDHIT uses for it's initial filtering step. Shorter lengths are more accurate but slower. 

In Panaroo, we chose to use the shortest option to prioritise accuracy over speed.

**Comment by raghuramdr** [comment]
Thanks for the explanation!
