### ISSUE TITLE
Add a descriptive error message when you have 0 core genes

### ISSUE THREAD

**Issue by bruzecruise** [gtonkinhill/panaroo#243]
Hello - I'm a huge fan of this software! 

I spent way too much time recently trying to understand why the core genome alignment step kept failing for a clade of bacteria - trying to identify any issue with my file formats or my panaroo environment. But it turns out the problem was that my bacteria clade was too diverged and shared 0 core genes! I was wondering if you could add in a descriptive error message for this rare occurrence in case future users have my same problem. 

Thanks!

**Comment by gtonkinhill** [comment]
I've now added a new message in the latest release.
