### ISSUE TITLE
Conda installation: pkg_resources module not found

### ISSUE THREAD

**Issue by sreerampeela** [gtonkinhill/panaroo#245]
Hi, I am trying to run the Panaroo script installed via conda in a new environment panaroo_env following the installation instructions (panaroo>=1.3). However, I am getting an error, ModuleNotFoundError: No module named 'pkg_resources'. Below is the full log:
Traceback (most recent call last):
  File "/home/sreeram/.local/bin/panaroo", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

I tried installing setup tools after referring to https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources , but the module was already present in  /home/sreeram/.local/lib/python3.8/site-packages (65.4.1). I am using WSL2 in windows 11.

**Comment by gtonkinhill** [comment]
Hi,

I haven't tried installing panaroo with windows/WSL2 before. However, it looks like the python module location is not referring to your conda installation for some reason. There should be a reference to the location of the conda environment in `/home/sreeram/.local/lib/python3.8/site-packages`

I'm afraid I don't know how to fix this. You might need to ask someone who has experience running Conda/Linux on windows.
