### ISSUE TITLE
What does "~~~" mean in the gene_presence_absence.csv file?

### ISSUE THREAD

**Issue by bridgeto** [gtonkinhill/panaroo#246]
I have quite a few gene names listed under the Gene column, specifically with "~~~" separating them. For example, "higA~~~higA_2~~~higA_1". Just curious what the "~~~" indicates?  Thanks.

**Comment by nzmacalasdair** [comment]
Hello! We get this question decently often, ie (#238 ), the tildes are just an uncommon separator used to separate all the different gene names assigned to a gene cluster in the original annotations input into panaroo.
