### ISSUE TITLE
Discrepancy in Gene Counts between summary_statistics.txt, pan_genome_reference.fa, and gene_presence_absence.csv

### ISSUE THREAD

**Issue by Dx-wmc** [gtonkinhill/panaroo#248]
Hi,

I've been using panaroo for some time, and today I stumbled upon an inconsistency that I'd like to address. I've noticed that the number of genes in the pan_genome_reference.fa is only 4,352. However, both the summary_statistics.txt and the gene_presence_absence.csv indicate a count of 4,378 genes. I'm curious, why is there this discrepancy in the gene counts among these files?

**Comment by gtonkinhill** [comment]
Hi,

This is because multiple paralogous clusters for the same family are only represented once in the `pan_genome_reference.fa` file. This is to avoid issues with multi-mapping when aligning reads to the reference file.

I hope this helps!

**Comment by Dx-wmc** [comment]
> Hi,
> 
> This is because multiple paralogous clusters for the same family are only represented once in the `pan_genome_reference.fa` file. This is to avoid issues with multi-mapping when aligning reads to the reference file.
> 
> I hope this helps!

I frequently rely on the gene_presence_absence.csv file to investigate specific genes of individual bacteria. Based on your explanation, this file includes paralogous gene clusters, which might lead to potential misinterpretations when analyzing certain genes. Does Panaroo offer a separate list or a method to identify these paralogous clusters? I greatly appreciate your assistance. Thank you.

**Comment by gtonkinhill** [comment]
Hi,

It is possible to get Panaroo to collapse paralgous clusters using the `--merge_paralogs` option. 
A flag is also available in the `final_graph.gml` file which will indicate which clusters are paralogs.

**Comment by Dx-wmc** [comment]
> Hi,
> 
> It is possible to get Panaroo to collapse paralgous clusters using the `--merge_paralogs` option. A flag is also available in the `final_graph.gml` file which will indicate which clusters are paralogs.

Thank you for your warm and quick reply!
