### ISSUE TITLE
presence absence grid question

### ISSUE THREAD

**Issue by waalkes** [gtonkinhill/panaroo#249]
I love Panaroo.  Thanks for your efforts writing it.

I am looking at a presence absence grid and have found this (or similar) in a number of cases: 1_refound_20

I have tried to figure out what it means but have been unsuccessful.  Can you describe what it means?

Thanks,

Adam

**Comment by gtonkinhill** [comment]
Hi,

Thanks very much, this indicates that the  gene sequence was found by Panaroo but was not included in the original annotations. The first number is the index for the genome used internally by Panaroo and the last number is the index that keeps track of the total number of genes that have been re-found in the entire Panaroo run.

I hope this helps and let me know if I can clarify anything further.

**Comment by waalkes** [comment]
Thanks.  To confirm, the initial annotation in the gff file did not find the gene but panaroo found it in the FASTA DNA at the bottom of the gff file.  Correct?

So, I should think of this gene as being present in the sample.  

Is there any place in the panaroo output where I can find the DNA for these "found" by panaroo genes?  I could blast the gene from another sample against the nucleotides of the one that hadn't found it but if it is already in the output that would be easier.

Thanks again,

Adam

**Comment by gtonkinhill** [comment]
Hi Adam,

Yes, that's correct. The sequence should be included in the `gene_data.csv` file. 

Panaroo has less stringent requirements for calling a gene than tools such as Prodigal. For example, sometime these gene sequences may be fragmented.
