### ISSUE TITLE
Clustering id confirmation

### ISSUE THREAD

**Issue by gavinmdouglas** [gtonkinhill/panaroo#250]
Hi there,

Thanks again for developing and maintaining Panaroo.

Quick question: do the values in the `clustering_id` column of `gene_data.csv` (e.g., 0_0_0) contain the genome, scaffold, and gene number respectively? With the gene number being the actual order on the scaffold? It looks like this is the case, but I just wanted to ensure I could safely interpret these values like this for a downstream analysis with many output files.

Thanks,

Gavin

**Comment by gtonkinhill** [comment]
Hi Gavin,

Yes, that's correct. One thing to note is that these numbers aren't updated to account for refound genes.

**Comment by gavinmdouglas** [comment]
Thanks for confirming!


Cheers,

Gavin
