### ISSUE TITLE
gene presence/absence file having ";" without merging paralogs

### ISSUE THREAD

**Issue by mhjonathan** [gtonkinhill/panaroo#257]
Hi,

I'm running the Panaroo with gff3 files without merging paralogs in strict mode.

panaroo  \
            --threads 20 \
            --input {input} \
            --out_dir {out_dir} \
            --clean-mode strict \
            --remove-invalid-genes \
            --threshold 0.98 \
            --family_threshold 0.7

And when I check gene_presence_absence.csv file, there are some queries like below (Yellow marked):

![image](https://github.com/gtonkinhill/panaroo/assets/97439815/5499fcb0-001f-42fc-8bd6-9829cae4d99e)

They are not paralogs, almost no similarity between those queries. Can you tell me what are them?

**Comment by gtonkinhill** [comment]
Hi,

This is usually caused by fragmented genes which Panaroo will merge together. 
Depending upon the reading frame they were originally called in, they can look different from the other genes in the cluster, so it is important to also consider the DNA sequence when comparing them.

**Comment by mhjonathan** [comment]
Hi, thank you for the answer.

Then how can I deal with this problem? I expect fragmented genes would be filtered out with --remove invalid-genes option. It can draw incorrect conclusion with clustering gene with fragmented gene that has no connection each other, right?

**Comment by gtonkinhill** [comment]
Hi, 

Sorry, I missed your reply. The `--remove-invalid-genes` filters out invalid GFF entries but not fragmented gene calls. Instead, Panaroo merges these together with the ';' as a delimiter.
