### ISSUE TITLE
clustered_proteins file in output? 

### ISSUE THREAD

**Issue by qianxuans** [gtonkinhill/panaroo#266]
Hey, 
Is there any file in the output that is in the same format as clustered_proteins from the roary output? An example of clustered_proteins is like: 
https://github.com/sanger-pathogens/Roary/blob/master/t/data/clustered_proteins

If not, is there any script available that can generate the file like clustered_proteins? 

Thank you so much for the help!

**Comment by gtonkinhill** [comment]
Hi,

I'm afraid not. Although, I think you should be able to produce a similar output by combining the information in `gene_data.csv` and `gene_presence_absence.csv`
