### ISSUE TITLE
Wrong IDs in pangenome reference fasta

### ISSUE THREAD

**Issue by LucoDevro** [gtonkinhill/panaroo#269]
Hi, 

I am using the pangenome reference fasta file to get COG annotations from eggNOG, yet I noticed the record IDs are identical for all entries. I didn't have this issue when I was using release 1.3.4, yet I recently updated to the most recent version (1.4.1) because I faced the same issue as in #258. I digged a bit into the code and it appears that the pangenome reference file function has been updated substantially since release 1.3.4. Unfortunately, the `node` variable from which panaroo gets the ID, is not being updated while generating SeqRecords.
https://github.com/gtonkinhill/panaroo/blob/735065d8a32ff043bd211c189ea4556660401959/panaroo/generate_output.py#L160-L181

Maybe you need another for loop or move that entire second chunk of code into the previous loop?

An example output from one of my runs: [pan_genome_reference.zip](https://github.com/gtonkinhill/panaroo/files/14347807/pan_genome_reference.zip)

**Comment by gtonkinhill** [comment]
Hi, thanks very much for raising this. I'll take a look and try to get a fix released soon.

**Comment by gtonkinhill** [comment]
Thanks very much for testing it and pointing out the issue in the first place!
I will hopefully have an updated release with the fix included in the next day or two.
