### ISSUE TITLE
Cd-hit-est problem

### ISSUE THREAD

**Issue by anagaga27** [gtonkinhill/panaroo#285]
Hello, 
I'm trying to run panaroo but this problem came out: 

subprocess.CalledProcessError: Command 'cd-hit-est -T 10 -i /home/agargam/TFM/Archivos gff/Archivos_GFF/CV_Schmerer_Salmeron_Carlos_Green/output_moderate_Carlos_2/tmp8kkiizc9/tmphnvod1mo -o /home/agargam/TFM/Archivos gff/Archivos_GFF/CV_Schmerer_Salmeron_Carlos_Green/output_moderate_Carlos_2/tmp8kkiizc9/tmpmyti8td1 -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7 > /dev/null' returned non-zero exit status 1.

The first time I ran panaroo I had no problem, and I'm using the same parameters as then. 
Do you know why this error happens?

Thank you.

**Comment by nzmacalasdair** [comment]
Hello, I thin this is almost definitely the same issue as #284. We've seen similar issues in the past (eg #247 and #253), and been unable to reproduce the error. It seems very likely to be a problem with the installation -- could you let me know how you installed panaroo, and also try running the cd-hit-est  command on the file separately?

`cd-hit-est -T 10 -i /home/agargam/TFM/Archivos gff/Archivos_GFF/CV_Schmerer_Salmeron_Carlos_Green/output_moderate_Carlos_2/tmp8kkiizc9/tmphnvod1mo -o /home/agargam/TFM/Archivos gff/Archivos_GFF/CV_Schmerer_Salmeron_Carlos_Green/output_moderate_Carlos_2/tmp8kkiizc9/tmpmyti8td1 -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7`

**Comment by anagaga27** [comment]
I've tried running the cd-hit-est command on the file separately, but I just get cd-hit options.
I've reinstall panaroo in another new environmet, but the same error came out.

I install panaroo with mamba, as is specified in docs/gettingstarted/installation.md:

conda install mamba -c conda-forge
mamba install -c conda-forge -c bioconda -c defaults 'panaroo>=1.3'

**Comment by nzmacalasdair** [comment]
Sorry, is there no error message when you try and run the cd-hit command outside of panaroo? If you could upload the message you see here when trying to run the command that would be great. It's also worth double checking that you're running it with the conda environment in which panaroo is installed active.

**Comment by nzmacalasdair** [comment]
Hi,

Thanks for your patience. I did some additional testing today and was unable to reproduce this error using the same version (v4.8.1) of cd-hit, which makes me wonder if this is actually a problem with the generation of the input files during this step of panaroo.

Can I ask what platform (particularly which OS) you are using to run panaroo? Also, if you would also be willing to share a small dataset which can reproduce the error, that would allow me to investigate further.

Finally, to double check that this is not an install error, you could try running the cd-hit command on another file, for instance:

`cd-hit-est -T 10 -i combined_DNA_CDS.fasta -o test1.cdhit -c 0.99 -s 0.0 -aL 0.0 -AL 99999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7`
