### ISSUE TITLE
 cut-off of 100% aa identity not working properly 

### ISSUE THREAD

**Issue by memoriasresiduais** [gtonkinhill/panaroo#286]
dear all,

is there a way to separate gene families using a cut-off of 100% aa identity (i.e. each gene family in the pangenome should only correspond to one single protein variant)?

The parameters 
--family_threshold 1 --len_dif_percent 1 --merge_paralogs
still pool together proteins with up to 98% aa identity.

btw, the same problem happens w/roary (https://github.com/sanger-pathogens/Roary/issues/616)

thanks in advance for your feedback.

cheers,
mem

**Comment by gtonkinhill** [comment]
Hi,

You will also need to adjust the `--threshold` parameter which controls the initial clustering.
I hope this helps!
