### ISSUE TITLE
Query Regarding Discrepancy in Output Information for Dataset of 3245 GFF3 Files

### ISSUE THREAD

**Issue by 2021JohnSheng** [gtonkinhill/panaroo#288]
"I am currently working with a dataset comprising a total of 3245 GFF3 files. However, the output information displays as below:
 
![image](https://github.com/gtonkinhill/panaroo/assets/89462632/52d7be9e-79f9-4a9f-aa21-9620961dc3de)

Can you please provide clarification on this discrepancy?"

**Comment by gtonkinhill** [comment]
Hi,

If you are using multiple threads the files will be grouped into chunks which is what the process bar reports.
I hope this helps!

**Comment by 2021JohnSheng** [comment]
> Hi,
> 
> If you are using multiple threads the files will be grouped into chunks which is what the process bar reports. I hope this helps!



> Hi,
> 
> If you are using multiple threads the files will be grouped into chunks which is what the process bar reports. I hope this helps!
"Thanks for clearing that up! Really appreciate the explanation!"

**Comment by 2021JohnSheng** [comment]
> Hi,
> 
> If you are using multiple threads the files will be grouped into chunks which is what the process bar reports. I hope this helps!
"Thanks for clearing that up! Really appreciate the explanation!"

**Comment by 2021JohnSheng** [comment]
@gtonkinhill "Thanks for clearing that up! Really appreciate the explanation!"
