### ISSUE TITLE
Errno 24 when running panaroo

### ISSUE THREAD

**Issue by svanhal71** [gtonkinhill/panaroo#29]
Hi I get the error message below when trying to run panaroo.

 panaroo -i *.gff -o results  error: argument -i/--input: can't open 'E1042_BEL_2011.gff': [Errno 24] Too many open files: 'E1042_BEL_2011.gff'
I have deleted this file and get the same error with the next file in the list. The files are all similar sizes. I also get the same error when running: panaroo-qc 

plot_panaroo_qc: error: argument -i/--input: can't open 'E1040_BEL_2011.gff': [Errno 24] Too many open files: 'E1040_BEL_2011.gff'

Any suggestions?

**Comment by nzmacalasdair** [comment]
Hi!
Yes, this is a known issue where we open all the files at once to read them in, but in some environments run into an issue with trying to open that many files at once. 

This default behaviour may change in a future version, but for now the easiest thing to do is just increase the limit of files you can have open at once, by running the following command:

` ulimit -n 123` 

where 123 is some number greater than the number of gffs you're trying to run panaroo with. You should be able to run panaroo fine afterward.

**Comment by svanhal71** [comment]
Have tried this - still get the same error

I have also stopped everything else and only run panaroo - same error
I doubled the fs.file-max number - same error
I have included a nofile line in the limits.config file - same error

Have installed it on another linux (ubuntu 16.04) computer with ulimit -n 123 - same error.

Further thoughts?

**Comment by tseemann** [comment]
What does `ulimit -a` say?

**Comment by svanhal71** [comment]
Thanks Torsten that helped. 

For those using ubuntu 16.04 you need to modify the following:

    /etc/systemd/user.conf
    /etc/systemd/system.conf, and

change the following line: DefaultLimitNOFILE=4056 

In
  /etc/security/limits.conf

add:
*       soft    nofile  4056
*       hard    nofile  4056

It worked for me after that.

**Comment by gtonkinhill** [comment]
Panaroo now closes files it is not currently reading/writing which should remove this problem in most cases.
