### ISSUE TITLE
Panaroo run time

### ISSUE THREAD

**Issue by anuradhasingh15** [gtonkinhill/panaroo#290]
What is the runtime for panaroo for approximately 15000 genomes. Is it standardized for that volume of data. In my case I am usign 40 threads and more then 300 hrs. have passed it's sill running. Any help will be appreciated.

**Comment by nzmacalasdair** [comment]
Hello,

Panaroo runtime is primarily determined by the complexity of the pangenome graph, which is affected by the number of isolates, as well as the size of the isolates' genomes. 

It is possible to run panaroo directly on datasets of ~10,000 isolates, but only when the genome size is small. In species with very large genomes, even smaller datasets can begin to take a very long time to run.

In these cases, we suggest running panaroo separately on subsets of the data, and then running `panaroo-merge` to combine the output of the subsets into a single pan-genome output file.

There is some documentation on using `panaroo-merge` here: https://gthlab.au/panaroo/#/merge/merge_graphs

**Comment by anuradhasingh15** [comment]
Thanks for the suggestion.

I tried Panaroo-merge, but it has been running for the past 15 days.

My dataset consists of 15,000 bacterial genomes, each ranging in size from approximately 4 to 7 MB.

Could you please  further help me?

**Comment by gtonkinhill** [comment]
Hi,

It sounds like your dataset is quite diverse given the range in genome sizes. In this case it can take Panaroo quite a long time to merge such a large set. We are working on improving this but it won't be ready for a while.

**Comment by anuradhasingh15** [comment]
Okay. Thanks for clarification.

**Comment by codebuzer** [comment]
we should shift towards PanTA for wall time and memory usage

**Comment by anuradhasingh15** [comment]
> we should shift towards PanTA for wall time and memory usage

@codebuzer 

I didn’t have a better experience with PanTA either, likely due to the high diversity of the target species and the large dataset. In such cases, I suppose subsampling or selecting a representative set works better. Let me know if you come across anything.
