### ISSUE TITLE
Recovering gene coordinates

### ISSUE THREAD

**Issue by theodorross** [gtonkinhill/panaroo#291]
Is it possible to recover the coordinates and strand (+/-) for gene annotations within assemblies?  I was hoping to find it in gene_data.csv but it's unfortunately not there.

Thanks in advance.

**Comment by gtonkinhill** [comment]
Hi,

You should be able to generate updated GFF files for each sample with this information using the `panaroo-generate-gffs` command.

**Comment by theodorross** [comment]
Hello,

Thank you, this worked perfectly!
