### ISSUE TITLE
Gene clusters annotation

### ISSUE THREAD

**Issue by anaGaGa98** [gtonkinhill/panaroo#294]
Hello!
First of all, thank you for developing Panaroo. It's such a great tool. 
My question is related to the annotation of the clusters of gene that we have as result in the gene_presence_absence.csv, column "gene". 
Maybe this is such a stupid queston...Do we know the database annotation that has been used to annotate these clusters? 
I've obtained the pangenome of _Neisseria ghonorreae_ and I need to do the functional annotation of the accesory genome using GO or KEGG terminology, so I need to know what type of annotation was used in order to be able to obtain the equivalent anotation on GO.

Thank you in advance! ^^

**Comment by gtonkinhill** [comment]
Hi,

Panaroo uses the gene names that were included in the original gff files. So it will depend on the annotation tool you used to call genes originally (i.e prokka/bakta). 

I hope this helps and feel free to ask further questions.
