### ISSUE TITLE
Invalid file extension

### ISSUE THREAD

**Issue by MHassanSaeed** [gtonkinhill/panaroo#295]
Hi,
I am using the following command to run Panaroo and getting a file extension error. I annotate the genome using prokka. Besides that, I tried using the off file from NCBI but still got the error.

panaroo -i Ent-11.gff -o entomo-prokka -a core --core_threshold 0.90 --merge_paralogs --clean-mode strict --aligner mafft --remove-invalid-genes -t 40
```
Traceback (most recent call last):
  File "/usr/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/usr/envs/panaroo/lib/python3.9/site-packages/panaroo/__main__.py", line 328, in main
    files.append(create_temp_gff3(line[0], line[1], temp_dir))
  File "//usr/envs/panaroo/lib/python3.9/site-packages/panaroo/prokka.py", line 102, in create_temp_gff3
    raise RuntimeError(f"Invalid file extension! ({ext})")
RuntimeError: Invalid file extension! ()
```

Thank you.

**Comment by gtonkinhill** [comment]
Hi,

Panaroo requires multiple GFF files to build a pangenome. As you are supplying only one (`Ent-11.gff`), it is assuming the file should be a list of paths to other GFFs which is causing the error.
