### ISSUE TITLE
Panaroo reporting genes of very different lengths together in the same gene family - Expected Behaviour?

### ISSUE THREAD

**Issue by NickJD** [gtonkinhill/panaroo#299]
Hi.
I have run Panaroo on a set of 10 E.coli genomes for some evaluation separate from this reported 'problem'.

One of the groups, 7407, show something I don't quite understand. It has 'clustered' together two genes that while do share some sequence identity at their start, are very very different in length (180bp and 2,664 bp).
![image](https://github.com/user-attachments/assets/53165b6d-246f-4c28-99ec-322bbd1c1f25)
![image](https://github.com/user-attachments/assets/ffcd3685-6f8f-47b4-8e9a-026cb4a89ac9)
The alignment can be seen below: 
![image](https://github.com/user-attachments/assets/47e1148b-3adb-4cd9-8dc0-0a83b2662241)
The CD-HIT results show that these two genes DO NOT cluster together (I guess because of the length difference).

Is this expected Behaviour?

**Comment by gtonkinhill** [comment]
Hi,

Yes, by default Panaroo will merge these sequences as they are often driven by fragmented assemblies or mis-annotation. 

At the moment, we have not exposed the length parameter of CD-HIT in the family clustering step where these sequences will be collapsed. You might be able to adjust the `--length_outlier_support_proportion` parameter to force clusters like these to be split.

If this is something a few people are interested we could look into adding the option to specify a length restriction as well as the family identity threshold.

**Comment by iqbal-lab** [comment]
I'd be interested in the ability not to split them  but to discard the smaller incomplete one. I'd like to be able to just get complete gene alleles  and essentially ignore genes that are impacted by contig ends .

**Comment by gtonkinhill** [comment]
Hi Zam,

We might be able to do this as a post-processing step using the length outlier flags that Panaroo currently adds to sequences in the `gene_presence_absence.csv` file. I'll have a look at how the two options might be added when I get a chance.

**Comment by iqbal-lab** [comment]
Cc @Danderson123

**Comment by NickJD** [comment]
Hi both, 
I think it would be wrong to assume that these smaller sequences are going to always be 'incomplete' versions of the larger ones. Many genes share domains etc.
The two examples I provided at the top hit different genes in a few searches I conducted (~99% query and subject coverage).

As you have already discussed, more flags and options for the user to decide would obviously be beneficial.

**Comment by Danderson123** [comment]
Hi @NickJD, are you running panaroo using the default parameters? If so see #300.

**Comment by NickJD** [comment]
@gtonkinhill - Could I ask another question.
If for example we had a gene family as described above but that shorter sequence we see is from the same genome (think, broken copy etc), are both sequences added to the concatenated MSA?

Hope that makes sense - Basically I want to know how are these incidents dealt with when there are >=2 copies per genome.

**Comment by gtonkinhill** [comment]
Hi Nick,

At the moment we just include the longest of the fragments in the MSA. This isn't ideal and will hopefully be improved in the next version of Panaroo.

**Comment by NickJD** [comment]
So for each gene family/ group, you use the longest fragment (or pick randomly if two of the same size) for the MSA. 

This makes sense as I have been trying to read the code but it gets quite confusing at points :smile:

**Comment by gtonkinhill** [comment]
I've added the option (`--family_len_dif_percent`) to specify an additional length requirement at the gene family clustering step. This will be available in the next release.

@iqbal-lab @Danderson123 
To get cleaner MSAs, I would recommend combining the strict re-find mode with a higher gene family length overlap precentage. i.e.
`--clean-mode strict --refind-mode strict --family_len_dif_percent 0.7`

This should remove most erroneous annotations from making it into the final MSAs.

**Comment by gtonkinhill** [comment]
This is now available in v1.5.1

**Comment by NickJD** [comment]
Will test it out. Thanks
