### ISSUE TITLE
Is networkx 2.4 truly incompatible with panaroo?

### ISSUE THREAD

**Issue by tseemann** [gtonkinhill/panaroo#30]
```
ERROR: panaroo 0.1.0 has requirement networkx==2.3,
 but you'll have networkx 2.4 which is incompatible.
```

**Comment by gtonkinhill** [comment]
They have changed the name of a function and I haven't yet updated it so have restricted the version as a stopgap. The compatibility should be fixed soon.

**Comment by gtonkinhill** [comment]
Panaroo should now work with the latest networkx.
