### ISSUE TITLE
Default CD-HIT length different percent different than displayed in help message

### ISSUE THREAD

**Issue by Danderson123** [gtonkinhill/panaroo#300]
Hi @gtonkinhill,

Not sure if it is related but I saw #299 and remembered coming across this. The panaroo help message states the default value for `--len_dif_percent` is 0.98 but https://github.com/gtonkinhill/panaroo/blob/e928a7acc8340389201545052d23e0495484126a/panaroo/cdhit.py#L51 seems to suggest it is in fact 0, potentially explaining why some sequences with very different lengths are stuck together by default.

Best wishes,
Daniel

**Comment by gtonkinhill** [comment]
Hi Daniel,

This is the default in the `cdhit` function but is overwritten by `len_dif_percent` argument in the `__main__.py` file.

The clustering of sequences with very different length occurs at the subsequent family clustering step which only considers sequences in the local neighbourhood of the graph. Here, we do not currently have a length requirement and only cluster on sequence identity.

I'll try and add an option to specify an additional length restriction in the next Panaroo release. It might be a few weeks before I'm able to get to it but I'll close this issue for now and post updates in #299

**Comment by Danderson123** [comment]
Thanks for getting back to me and my apologies @gtonkinhill you are right, I had completely missed this line https://github.com/gtonkinhill/panaroo/blob/e928a7acc8340389201545052d23e0495484126a/panaroo/__main__.py#L291. 

Best wishes, 
Daniel
