### ISSUE TITLE
Get Multifasta or alignment for each CDSs

### ISSUE THREAD

**Issue by nbat64** [gtonkinhill/panaroo#302]
Hello,

Thank you for your software, it is really useful. I am comparing it with others tools (e.g. get_homologues.pl) and I will be interested to get from outputs multifasta or alignments per orthologous genes of core and cloud for following analyses (gene tree / selection test).

Do they exist as intermediate files before concatenation and alignment?

Thank you

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the slow reply. Individual gene alignments should be available in the `aligned_gene_sequences` folder after running panaroo with the alignment parameter.
