### ISSUE TITLE
Potential bug in panaroo

### ISSUE THREAD

**Issue by Hocnonsense** [gtonkinhill/panaroo#303]
I'm reading the code of panaroo, and I've found something difficult to understand

One is in cdhit.py, is it a typo for "as=AS"? it may be
```python
            run_cdhit(
                ...
                aL=aL,
                AL=AL,
                aS=aS,
                AS=AS,
                ...
            )
```
in
https://github.com/gtonkinhill/panaroo/blob/e928a7acc8340389201545052d23e0495484126a/panaroo/cdhit.py#L186-L210

Another is in generate_network.py, I think genes at the end of contigs should be marked as `node['hasEnd']=True`
https://github.com/gtonkinhill/panaroo/blob/e928a7acc8340389201545052d23e0495484126a/panaroo/generate_network.py#L69-L78
However, at the end of cycle, the last gene was ignored.
https://github.com/gtonkinhill/panaroo/blob/e928a7acc8340389201545052d23e0495484126a/panaroo/generate_network.py#L226-L228
Is it necessary to add another check for it such as:
```python
    if prev is not None:  # end of cycle
        G.nodes[prev]["hasEnd"] = True

    return G, centroid_context, seqid_to_centroid
```

Thanks if you could reply!

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the delayed reply, and thank you very much for flagging these issues.

The first is indeed a typo, which I will fix in the next release. However, it should not affect the output, as Panaroo only uses global alignment (use_local=False), which overrides this parameter.

The second issue appears to be a potential bug, although it would likely have a very small impact on the output. It could result in at most one miscalled gene if an annotation error occurred in the last gene processed by Panaroo. I will investigate this further and fix it if necessary in the next release.
