### ISSUE TITLE
panaroo merge does not produce combined_protein_CDS.fasta

### ISSUE THREAD

**Issue by revinici** [gtonkinhill/panaroo#308]
As the title says. And the merge command also be updated to produce the combined_protein_CDS.fasta? Is there another way to generate this after merge results?

**Comment by gtonkinhill** [comment]
Hi,

All the information in `combined_protein_CDS.fasta` should be available in the `gene_data.csv` file after using the merge command.
The exception will be genes filtered out by Panaroo.
I hope this helps!

**Comment by revinici** [comment]
Yes, thank you. Users can generate the file with this command:

```bash
awk -F',' 'NR > 1 { print ">" $3; print $5 }' gene_data.csv > combined_protein_CDS.fasta
```
