### ISSUE TITLE
Low number of genes as output

### ISSUE THREAD

**Issue by AzizHN** [gtonkinhill/panaroo#309]
I run a panaroo test using 2 gff files, containing 1758 and 1553 genes, but  in summary resulted from panaroo (strict clean-mode) I have this: 
Core genes	(99% <= strains <= 100%)	26
Soft core genes	(95% <= strains < 99%)	0
Shell genes	(15% <= strains < 95%)	1
Cloud genes	(0% <= strains < 15%)	0
Total genes	(0% <= strains <= 100%)	27

**Comment by gtonkinhill** [comment]
Hi,

It is usually best to run panaroo on at least 10 genomes when using the strict mode. I would try running it using the sensitive option if you are only interested in a couple of genomes.
