### ISSUE TITLE
Panaroo Processing Inquiry

### ISSUE THREAD

**Issue by AzizHN** [gtonkinhill/panaroo#311]
Hello,

I am using Panaroo with 70 GFF files (bacterial species within the same family). This is my command:
`panaroo -i *.gff -o results_panaroo --clean-mode strict
I forgot to adjust the number of threads (so it's 1 by default according to documentation). After 48 hours, it is still running at the following stage:

**Total CPU time: 3250.98
Generating initial network...
Processing paralogs...
Progress: 100% | 451/451 [00:00<00:00, 1593.89it/s]
Collapsing mistranslations...**

Should I wait a little longer or adjust the number of threads?

**Comment by gtonkinhill** [comment]
It looks like it's about half way through so it's hard to say.
