### ISSUE TITLE
Error in collapse mistranslations

### ISSUE THREAD

**Issue by karthick1087** [gtonkinhill/panaroo#37]
Iam getting following error
collapse mistranslations...
Traceback (most recent call last):
  File "/home/giga/anaconda3/bin/panaroo", line 11, in <module>
    load_entry_point('panaroo==0.1.0', 'console_scripts', 'panaroo')()

**Comment by gtonkinhill** [comment]
This looks like it might be a problem with the installation. Did it print anything else and/or could you send me an example dataset that reproduces the error?

A first thing to try might be to install it in a clean conda environment

```
conda create -n pan python=3
conda activate pan
conda install -c bioconda/label/cf201901 panaroo
```

**Comment by karthick1087** [comment]
Thank you, it solved the problem......
