### ISSUE TITLE
Example .gff inputs

### ISSUE THREAD

**Issue by aysunrhn** [gtonkinhill/panaroo#38]
Hi,

I was trying to run panaroo with a couple of gff files from RefSeq database, but I guess they had some problems. One was with sequencing not being divisible by 3, which I understand but the other error didn't have any other explanation that could help. It is raised at the end of parsing function, so I think it must be a problem way before that:

https://github.com/gtonkinhill/panaroo/blob/11442bc68591dc3d06c4611eedbb29f62085ad7e/panaroo/prokka.py#L200-L224

I re-annotated the fasta files using prodigal, and panaroo seems to work fine with prodigal output. I looked though the repo and couldn't find any example gff inputs, is it possible if you could provide one? Or maybe you came across similar issues with annotations from RefSeq before? Thanks!

**Comment by aweimann** [comment]
Hi,

We did encounter some issues with RefSeq annotations before, which is why we eventually wrote a script to deal with the more common problems. You could try running your RefSeq GFFs through scripts/convert_refseq_to_prokka_gff.py and try it out yourself.

**Comment by aysunrhn** [comment]
Sorry my mistake, I must have missed that script! Looks like it worked, thanks!
