### ISSUE TITLE
--merge_paralogs option as a post-processing step?

### ISSUE THREAD

**Issue by aysunrhn** [gtonkinhill/panaroo#39]
Is it possible to have panaroo merge paralogs in a separate, post-processing step if the graph is already available? I see you have made such setup for alignment so I'm trying to find a way to implement this option in a similar way.

Also, I'm getting a valuerror on line 14 when I try the `--merge_paralogs` option
https://github.com/gtonkinhill/panaroo/blob/11442bc68591dc3d06c4611eedbb29f62085ad7e/panaroo/merge_nodes.py#L11-L14

I think it detects nodes with same IDs in the graph output, but I'm not sure how I can fix this issue, or why this should raise an error in the first place. I'd appreciate if you could help. Thanks!

**Comment by gtonkinhill** [comment]
Hi,

Thanks for flagging this. It should be fixed in the latest release on GitHub. This will be on bioconda soon.

It should definitely be possible to perform this merge as a post processing step, I will attempt to add this script in in the next release.

The current release also includes a decent speed improvement so hopefully re-running your data shouldn't take as long.

**Comment by aysunrhn** [comment]
No problem! Thanks for the quick fix. What was the issue? Do you suggest I repeat my runs without the merging as well? I'm wondering if those were affected.

Speaking of speed, Fig.7 on your preprint excludes the gene alignment step, right? I was trying this on a small dataset (70 bacterial strains), and it took longer than I expected (>4hr) so I'm not sure if this is because I didn't give it enough CPUs (used 6 only) or if it's a different issue.

**Comment by gtonkinhill** [comment]
I had recently moved the merging to a different stage of the pipeline and one of the assumptions I made was no longer valid. It should have no effect on run without merging though so no need to rerun.

Yes Fig. 7 was without MSA as these are the same between methods as they depend on the aligner used. The speed up should hopefully improve the pre alignment stage a fair amount.

**Comment by aysunrhn** [comment]
I see. Without the MSA, my run had ended around ~30 mins with 4 CPUs, so I was confused it exceeded 4 hours with MSA. Does it make sense for ~2000 core genes and 70 bacterial strains? I'm not sure sure how your program should scale.

**Comment by gtonkinhill** [comment]
Yes, generating MSAs for >2000 genes will take a while with only 4 CPUs. However, this stage of the pipeline benefits a lot from additional CPUs. Essentially panaroo just calls the requested aligner for each gene and thus this stage of the algorithm is reliant on the speed of the aligner.

**Comment by aysunrhn** [comment]
I have just managed to update my local install and try the fixed version, I encountered a different problem this time:

```bash
clean_network.py", line 435, in merge_paralogs
    temp_c.pop(),
KeyError: 'pop from an empty set'
```

https://github.com/gtonkinhill/panaroo/blob/69000f8bd8a1df1b57f3ab0a2096fe88b7bc3381/panaroo/clean_network.py#L430-L437

Maybe there should be a check for the cluster size since it looks like it's changing `temp_c` in place?

**Comment by gtonkinhill** [comment]
Hi,

Yes, you are completely right. This managed to slip by my test case. I've pushed the check to master so if you update by either pip or GitHub you should have the fix. 

Please let me know if you still run into an issue and thanks for helping to fix the problem!

**Comment by aysunrhn** [comment]
Hi, I finished running some tests with the current version, and it all seems to be working fine now.

No problem at all, glad I could help!
