### ISSUE TITLE
Refound gene tags

### ISSUE THREAD

**Issue by aysunrhn** [gtonkinhill/panaroo#40]
I'm analyzing the results of panaroo right now, I have a question about the refound genes. I'm trying to map the genes in each node to their original locus tags in the `gff` files. Here's an example of what I have:

I have a node labeled 501, it has the geneIDs `42_1_57;60_0_13;44_1_35;19_3_38;45_1_66;40_refound_2166...` and so on. So `42_1_57` means isolate 42, contig/scaffold 1 and CDS 57 (all 0-based). I see I can actually find this exact entry in `gene_data.csv` as `KAB03,NZ_CP017647.1,42_1_57,NZ_CP017647.1_cds3782,MTGN...` and easily extract all the information I need. 
But with refound genes it is a little different. Say, I want to map the `40_refound_2166` to its original locus tag, how do I interpret the tag assigned by panaroo? I understand the first number is the isolate index, but I couldn't figure out the second one. 

I hope I could explain the question, really appreciate if you could explain this part.

**Comment by gtonkinhill** [comment]
Hi,

This is a little tricky as for the refound genes there is no original locus tag. At the moment we output the protein and DNA sequences to gene_data.csv but not the location information. The final number in the refound gene name is just the order in which panaroo found it and so is not particularly helpful. 

As the sequence in gene_data.csv should exactly match that in the original GFF (or its reverse complement) you could use this to search for its location. I will have a think about how best to retain this information.

Its location in relation to other genes is available in the 'final_graph.gml' file which can be viewed in cytoscape.

Hopefully this helps a bit

**Comment by aysunrhn** [comment]
Hi, thank you for the quick response. Yeah, I understand why it is difficult now, and yes it is possible to see where the refound genes are on the graph but I think in some applications it could be very useful to keep track of the locations as knowing where the gene is located within the isolate, in the context of the whole genome. So I guess I'll leave this as a feature request. 

> As the sequence in gene_data.csv should exactly match that in the original GFF (or its reverse complement) you could use this to search for its location. I will have a think about how best to retain this information.

Yes, this works. I can track down where the gene is by just aligning it against the whole genome sequence. For instance, the one in my question (`40_refound_2166`) is actually on the plasmid, this could be interesting, I'll see if I can interpret what it means. Thanks!
