### ISSUE TITLE
Group name in pan_genome_reference.fa

### ISSUE THREAD

**Issue by RJBeng** [gtonkinhill/panaroo#41]
Hello, 

I was wondering if there is a way to see the group/gene name in the pan_genome_reference.fa file? 

Many thanks
Rebecca

**Comment by gtonkinhill** [comment]
Hi Rebecca,

At the moment this information is stored in the `final_graph.gml` file. The gene IDs given in `pan_genome_reference.fa` can also be matched to their original annotations by looking at the `gene_data.csv` file. 

I agree that having the gene/group name would be more informative in this file so will add it in the next release.

**Comment by gtonkinhill** [comment]
I've added this into the current release fc4c33055baaa2184aaae663ec15f356221dbcef. You can update your installation via GitHub or alternatively it should be on Bioconda in the next few days.

**Comment by RJBeng** [comment]
Thank you so much @gtonkinhill 👍 !
