### ISSUE TITLE
Detailed Tutorial Required

### ISSUE THREAD

**Issue by Kanwal03** [gtonkinhill/panaroo#42]
Hello I am using Panaroo for pangenome estimation. I didn't find a detailed tutorial where I can see how to use this pipeline effectively and how to utilize all of its functionalities. Rather a single command I saw in docs. After running that command I only got following files
combined_DNA_CDS.fasta
combined_protein_cdhit_out.txt.clstr  
gene_data.csv  pre_filt_graph.gml
combined_protein_cdhit_out.txt  
combined_protein_CDS.fasta
tmphdrk_kmh
I didn't find any gene presence/absence file and not any other pangenome/coregenome, accesory, 
How can I generate these files. 
Please provide a detailed tutorial like other pangenome estimation tools are providing.
Thank You.

**Comment by matbeale** [comment]
Hi, as described in the documentation, those files (including gene/presence absence matrixes) are generated as a final output of the pipeline. If you didn’t get those files, that suggests it’s failing. Could you provide error logs and details of your input files please?

**Comment by gtonkinhill** [comment]
If you are having issues with installation I would recommend using the Bioconda installation method described [here](https://gtonkinhill.github.io/panaroo/#/gettingstarted/installation). We have a more detailed description of the parameters for running Panaroo [here](https://gtonkinhill.github.io/panaroo/#/gettingstarted/params).  If you install using Bioconda and are still having issues it would be great if you could provide a small reproducible example to help diagnose the problem.
