### ISSUE TITLE
allow for adding genomes to existing pangenomes

### ISSUE THREAD

**Issue by marade** [gtonkinhill/panaroo#43]
Hi. Does Panaroo provide a means for adding genomes to an existing pangenome generated with Panaroo? How can one add genomes while maintaining the existing gene names?

**Comment by gtonkinhill** [comment]
Hi, 

At the moment I'm afraid there isn't a script for doing this. However, we are currently working on a script to merge graphs from different runs of Panaroo which could be used for adding new genomes. 

I will leave this issue open and update it when the script is available.

**Comment by marade** [comment]
Thanks for looking at this. Doing one-off pangenomes is great for getting a sort of snapshot of a cohort, but being able to maintain an ongoing pangenome ecosystem where new genomes are regularly integrated--without having to run everything again--can add significant value, which I'm sure you can appreciate.

**Comment by gtonkinhill** [comment]
The most recent release includes an improved merge-graph script. This is still experimental but can merge the results of different panaroo runs allowing for genomes to be added in batches. We are hoping to extend this to individual genomes in the near future.
