### ISSUE TITLE
algorithm to bring sanity to node names

### ISSUE THREAD

**Issue by marade** [gtonkinhill/panaroo#44]
Panaroo node names are unwieldy and not very useful. I propose a method similar to the code below to fix them. It changes names like so:

oqxB7_yofA_1__mdtB_2_hdfR_5_ttgI_4 -> oqxB7
hcaR_1_benM_2_hdfR_4_hdfR_9_hdfR_8_hdfR_5_hdfR_1_benM_1_hdfR_3_benM_5 -> hcaR_9
baeR_1__baeR_2_barA_2_rcsC_13_baeR_barA -> baeR_2
hdfR_4_hcaR_2_hdfR_1_hdfR_8_hcaR_3_hcaR_1_hdfR_7_benM_6_benM_1_hcaR_4_hdfR_10 -> hdfR_13

`
    names = []
    for node, data in G.nodes(data=True): names.append(data['name'])
    for node, data in G.nodes(data=True):
        if list(data['name']).count('_') > 1 or\
            (list(data['name']).count('_') == 1 and not\
            data['name'].split('_')[-1].isdigit()):
            t1 = data['name'].split('_')[0]
            t2 = '_'.join(data['name'].split('_')[:1])
            t3 = ''
            if data['name'].split('_')[-1].isdigit():
                t3 = '_'.join(data['name'].split('_')[-2:])
            else:
                t3 = data['name'].split('_')[-1]
            if not t1 in names:
                m.write('\t'.join([data['name'], t1]) + '\n')
                data['name'] = t1
                names.append(t1)
            elif not t2 in names:
                m.write('\t'.join([data['name'], t2]) + '\n')
                data['name'] = t2
                names.append(t2)
            elif not t3 in names:
                m.write('\t'.join([data['name'], t3]) + '\n')
                data['name'] = t3
                names.append(t3)
            else:
                success = False
                for x in range(1, 200):
                    t4 = t1 + '_' + str(x)
                    if not t4 in names:
                        m.write('\t'.join([data['name'], t4]) + '\n')
                        data['name'] = t4
                        names.append(t4)
                        success = True
`

**Comment by marade** [comment]
Sorry, hopefully better formatting now:

```
    names = []
    for node, data in G.nodes(data=True): names.append(data['name'])
    for node, data in G.nodes(data=True):
        if list(data['name']).count('_') > 1 or\
            (list(data['name']).count('_') == 1 and not\
            data['name'].split('_')[-1].isdigit()):
            t1 = data['name'].split('_')[0]
            t2 = '_'.join(data['name'].split('_')[:1])
            t3 = ''
            if data['name'].split('_')[-1].isdigit():
                t3 = '_'.join(data['name'].split('_')[-2:])
            else:
                t3 = data['name'].split('_')[-1]
            if not t1 in names:
                m.write('\t'.join([data['name'], t1]) + '\n')
                data['name'] = t1
                names.append(t1)
            elif not t2 in names:
                m.write('\t'.join([data['name'], t2]) + '\n')
                data['name'] = t2
                names.append(t2)
            elif not t3 in names:
                m.write('\t'.join([data['name'], t3]) + '\n')
                data['name'] = t3
                names.append(t3)
            else:
                success = False
                for x in range(1, 200):
                    t4 = t1 + '_' + str(x)
                    if not t4 in names:
                        m.write('\t'.join([data['name'], t4]) + '\n')
                        data['name'] = t4
                        names.append(t4)
                        success = True
```

**Comment by gtonkinhill** [comment]
Hi,

Whilst the node names can be unwieldy I think they are more informative. We currently trim this style to a maximum length but could add the possibility of a user customised name length parameter. I can see that this might be useful if downstream programs struggle with long names.

I will look at adding this in to the next release.

**Comment by marade** [comment]
I do understand why you'd want to preserve all the gene names for a node. I think that information would be more tractable if it was stored in a more structured way. The output files currently produced by Panaroo not only yield this hard-to-parse name, where underscores may or may not indicate a division between two gene names, and may or may not occur as dual underscores instead of single, but we also get other problematic issues of this sort. For example say you want to machine parse out each gene and its annotation per node from the final graph. If you get this:

    annotation "yabJ_4;rutC_2;yabJ_1"
    description "2-iminobutanoate/2-iminopropanoate deaminase;Putative aminoacrylate peracid reductase RutC"

...a knowledgeable human knows which of the two annotations to assign to each of the three genes, but how can one write a parser to do it properly? The same sort of thing happens in gene_presence_absence.csv, where you not only have to account for the underscore problem, but also extraneous semicolons, and again gene + annotation issues, e.g.

lrpC_2__lrpC_1,lrpC_2;;lrpC_1,HTH-type transcriptional regulator LrpC;Acetyltransferase;IS4 family transposase ISBce8,

That's three annotations for two genes if I'm counting correctly. Could this information not be better segregated?

I appreciate your time and effort.

**Comment by tseemann** [comment]
This is why I ended up using `~~~` as my separator in all my tools :-P
How to encode structured data _and_ have nice human readable versions is an ongoing challenge.

**Comment by gtonkinhill** [comment]
Okay I think I've got a better idea of the issue now. 

I agree that we could do a better job of allowing the names to be machine readable. I'll have a go at improving this for the next release and will probably go with Torsten's suggestion. 

In the meantime, all this data is available in a hopefully easy to parse format in gene_data.csv which can then be matched up with the nodes. I realise this file is quite large though so appreciate that it would be easier to have nicer names in the graph and presence/absence matrix

**Comment by gtonkinhill** [comment]
I've changed the delimiter in the latest release.
