### ISSUE TITLE
Typo in get_neighborhood.py

### ISSUE THREAD

**Issue by aysunrhn** [gtonkinhill/panaroo#46]
Noticed a small typo in script `get_neighborhood.py` On lines 6 and 100, function arguments are lower case `g` but inside the functions, it's capital `G`

https://github.com/gtonkinhill/panaroo/blob/517cc24ef9a0e9bcb2571c2a286c3e5803a6ce3f/scripts/get_neighborhood.py#L6

https://github.com/gtonkinhill/panaroo/blob/517cc24ef9a0e9bcb2571c2a286c3e5803a6ce3f/scripts/get_neighborhood.py#L100

**Comment by aysunrhn** [comment]
> Thanks for flagging this. I'll fix it for the next release.

No problems! I still ran into some problems when running the scripts after fixing the typo, but haven't had the time to look into it further. I'll see what the problem is and let you know, in the meantime, is the script working for you atm?

**Comment by aweimann** [comment]
It would be great to get some feedback on this. We have internally used that scripts for some of our own analyses but it's also not been extensively tested.

**Comment by gtonkinhill** [comment]
We have now updated this script so it should hopefully run smoothly in the latest release.
