### ISSUE TITLE
panaroo-qc error 24: too many open files

### ISSUE THREAD

**Issue by svanhal71** [gtonkinhill/panaroo#47]
Running panaroo on ubuntu 16 with 950 files.

Any suggestions?

Thanks

**Comment by tseemann** [comment]
your system limits files per process:
``` 
ulimit -n  
102400
```
often it is 4096 which is too small.
you can try increasing with `ulimit -n 16384` etc
but ultimately you will need sysadmin to alter `/etc/limits.conf` or similar.

**Comment by svanhal71** [comment]
Thanks that sorted the problem however I now get 
ERROR: could not open "refseq.genomes.k21.s1000.msh" for reading (downloaded from https://mash.readthedocs.io/en/latest/tutorials.html). 
Suggestions?
Thx

**Comment by gtonkinhill** [comment]
This looks like you might have a problem with the path to "refseq.genomes.k21.s1000.msh". Can you double check the file exists and is readable? You could try running "head" on the file.

**Comment by svanhal71** [comment]
The file is readable and have moved it to the same folder as the data - same error.

Thx

**Comment by tseemann** [comment]
What do these say:
```
realpath refseq.genomes.k21.s1000.msh
ls -lsa refseq.genomes.k21.s1000.msh
```

**Comment by svanhal71** [comment]
Thanks
Got it to work now.
