### ISSUE TITLE
Error in collapse gene families

### ISSUE THREAD

**Issue by rebeccajhall** [gtonkinhill/panaroo#48]
Hi, I'm running a data set of ~900 complete prokaryote genomes from NCBI and it has errored out at the 'collapse gene families' stage:

collapse gene families..
Traceback (most recent call last):
  File "/home/rhall/.local/bin/panaroo", line 11, in <module>
    load_entry_point('panaroo==1.1.2', 'console_scripts', 'panaroo')()
  File "/home/rhall/.local/lib/python3.6/site-packages/panaroo/__main__.py", line 280, in main
    quiet=(not args.verbose))
  File "/home/rhall/.local/lib/python3.6/site-packages/panaroo/clean_network.py", line 137, in collapse_families
    seqid_to_index[sid] = centroid_to_index[seqid_to_centroid[sid]]
KeyError: '948_1_102'

Do you have a suggestion for fixing this?
Many thanks!

**Comment by gtonkinhill** [comment]
Hi, 

We mainly support annotations files generated by PROKKA. Sometime GFF files from NCBI can lead to issues. We created a script `./panaroo/scripts/convert_refseq_to_prokka_gff.py` which attempts to convert GFF files from other sources.

This script has not had extensive usage though so please let me know if you encounter issues with it.

**Comment by rebeccajhall** [comment]
Hi, thanks for getting back to me so quickly. I've annotated the fna files from NCBI myself with prokka so I'm not sure if that's the issue. I have taken a subset of these prokka-annotated genomes and panaroo completed fine on these. I will go back to the genomes and see if the error could be in there.

**Comment by gtonkinhill** [comment]
If you can narrow it down to a smaller subset that causes the error I would be happy to take a look.

**Comment by rebeccajhall** [comment]
Thank you! I will do.

**Comment by gtonkinhill** [comment]
I'm closing this for now until we can narrow down the issue.
