### ISSUE TITLE
Querry regaring statistics and alignment

### ISSUE THREAD

**Issue by SumeetTiwari07** [gtonkinhill/panaroo#51]
Hi,
Panaroo default threshold for a gene to be in core if its there in 95% of the isolates. But the summary_statistics.txt file tells core is in between 99 to 100 % and soft core is in between 95 and 99%. 
While constructing the overall core-genes alignment does it considered only on core (99% to 100%) or its included the genes from soft-core (95% to 99) too?

Thanking you,
Sumeet

**Comment by gtonkinhill** [comment]
Hi,

The `--core_threshold` parameter controls the threshold for including genes in the core alignment. By default its set at 95% which includes the 'soft-core'.  We did this as we felt that 99% was often overly strict. If you wish to restrict this further you can use `--core_threshold 0.99`

The summary_statistics.txt threshold was set to match Roary's definitions to allow for easy comparison.
