### ISSUE TITLE
Any way to extract sequences of a gene for alignment elsewhere?

### ISSUE THREAD

**Issue by jamiethompson77** [gtonkinhill/panaroo#52]
My old machine is struggling to align one gene, which is super long.  Is there any way to extract the unaligned sequences of one gene for alignment in CIPRES?

**Comment by aweimann** [comment]
Hi Jamie,

If you are familiar with the command line I think what should work is to use samtools faidx to index the combined_DNA_CDS.fasta or combined_protein_CDS.fasta which allows fast access to these FASTA files i.e. first run
`samtools faidx combined_DNA_CDS.fasta`
Then you want to get the  geneIDs from the graph: Load the graph into Cytoscape, search for your gene family of interest and then copy all geneIDs into a separate file gene_ids.txt and make sure each gene id is on a separate line. Then run 
`xargs samtools faidx combined_DNA_CDS.fasta < gene_ids.txt > output.fna`
This will search all genes listed in gene_ids.txt and write them into output.fna.

Best wishes,

Aaron

**Comment by jamiethompson77** [comment]
Hi Aaron.

Awesome, thanks for such a great reply!  Very helpful.

Jamie

**Comment by nzmacalasdair** [comment]
Hi Jamie,

Just to add that temporary unaligned FASTA files are output for each gene in the tempdir, if you interrupted panaroo before the alignment was complete, the temporary unaligned FASTA file should still be there.

Cheers,

Neil
