### ISSUE TITLE
Gene coding table

### ISSUE THREAD

**Issue by MichWeb75** [gtonkinhill/panaroo#53]
Panaroo is a great approach and I am looking forward to use it. At the moment it is lacking a parameter to set the gene coding table to 11 or 4, depending on the organism studied. Otherwise I run into the following error:

```
 File "/lib/python3.6/site-packages/panaroo/prokka.py", line 161, in translate_sequences
    raise ValueError("Premature stop codon in a gene!")
ValueError: Premature stop codon in a gene!
```

**Comment by gtonkinhill** [comment]
Hi,

This is a good point. We will try and get this done for the next release.

**Comment by phiweger** [comment]
Is this still an issue @gtonkinhill ?

**Comment by hoelzer** [comment]
@gtonkinhill I would be also interested in using other gene code tables as it is also already implemented for `prokka`! Thanks!

**Comment by gtonkinhill** [comment]
Hi all,

Sorry for the wait — I've finally got around to tackling this. I've added a new option to change the codon table to any of those offered in [BioPython's generic tables](https://biopython.org/docs/1.75/api/Bio.Data.CodonTable.html).

The table can be specified using the new `--codon-table` parameter. At the moment it is currently only on the devel branch until I've done a bit more testing but you should be able to install this version using the following command.

```
pip install git+https://github.com/gtonkinhill/panaroo.git@devel
```
