### ISSUE TITLE
Presence/absence in Roary format issue

### ISSUE THREAD

**Issue by milnus** [gtonkinhill/panaroo#55]
I have noticed that in the gene_presence_absence__roary.csv file the columns giving the number of isolates pr. cluster and the number of sequences pr. cluster seems to have been switched around. 
I have run Panaroo with 10 genomes and the column giving number of isolates range between 1 and 50, whereas the column for number of sequences reach a maximum of 10.

**Comment by gtonkinhill** [comment]
Ah, you are completely right. I've swapped them back in the latest version on GitHub.
