### ISSUE TITLE
Meaning behind 'contextual information'

### ISSUE THREAD

**Issue by milnus** [gtonkinhill/panaroo#59]
In the papir for Panaroo it is stated: "Panaroo utilises gene contextual information to collapse diverse gene families that have been incorrectly split into multiple clusters during the initial pangenome graph creation".
What does 'contextual information' mean? My guess would be that surrounding genes in the pan-genome graph are considered, but how many up- and down-stream genes are considered?

**Comment by gtonkinhill** [comment]
Yes, you guessed right! The algorithm operates a bit like a zip by searching for forks in the graph (nodes with degree > 2) and then searching in the neighbourhood of these forks for genes that should be collapsed. It iteratively starts with a neighourhood of 1 then 2 and 3.
