### ISSUE TITLE
# isolates vs. # sequences in gene_presence_absence files

### ISSUE THREAD

**Issue by lillycummins** [gtonkinhill/panaroo#61]
Hi,
I've been using panaroo and noticed in my gene_p_a matrices that the # of isolates sometimes exceeds the total number of genomes whereas # of sequences is never above the total number of genomes - wondering if this is a mistaken column swap?

**Comment by gtonkinhill** [comment]
Hi, sorry for the slow response. This was an issue we've had previously but I had hoped it had been fixed. Could you confirm whether you are using the latest version 1.2.2?

**Comment by lillycummins** [comment]
Just checked - I've been using 1.1.2 so the update will solve this, thank you anyway!
