### ISSUE TITLE
PRANK related codon-aware alignment Error

### ISSUE THREAD

**Issue by wshropshire** [gtonkinhill/panaroo#62]
Hello, 

So it appears that when running panaroo with this command line prompt:
![Screen Shot 2020-06-23 at 9 32 22 AM](https://user-images.githubusercontent.com/34726302/85416934-a6d31680-b534-11ea-8da9-798748a7b5be.png)

I get the following error during the core gene alignment:
![Screen Shot 2020-06-23 at 9 31 53 AM](https://user-images.githubusercontent.com/34726302/85416968-b3f00580-b534-11ea-9886-2b49e15dd675.png)

It's worth noting that I have run the same 94 gff files with both the mafft aligner in panaroo. Additionally, I have run PRANK with the same version in the pathway for panaroo with roary (prank-170427). This likelihood == 0 error appears to have been an issue with previous prank-msa versions, however, it's never been the case when using any versions of roary-3.12.0 or higher. Any idea what the issue may be? Thanks!

**Comment by gtonkinhill** [comment]
Hi, thanks for flagging this. Have you installed Panaroo using conda? I haven't yet updated the conda recipe to include prank as requested in issue #50. If this is the problem installing the latest Prank should hopefully fix the issue. If this doesn't work would it be possible to attach a small example to help with debugging?

**Comment by wshropshire** [comment]
Hello and thanks for your quick response! 

I already had PRANK-v170427 on our HPC cluster installed and had installed panaroo-1.2.2 through pip3. I have a module file that puts PRANK in my pathway, in addition, PRANK begins to create MSA files up until it hits the dnaA fasta file. I'll provide 4 prokka generated gff files from the 95 total isolates I have. Let me know if you need any additional files and/or questions that may help debug. 
[debug_gff_files.zip](https://github.com/gtonkinhill/panaroo/files/4821118/debug_gff_files.zip)

**Comment by gtonkinhill** [comment]
Thanks for that. It looks like a PRANK issue that occurs on the dnaA gene as you suggested. I was able to recreate it with the command `prank -d=./panaroo_out/tmpfdd_polr/dnaA.fasta -o=dnaA -f=8 -codon`. However, after installing PRANK v.170427 using conda the issue appeared to be fixed. I wonder if this has something to do with the way PRANK was installed? Are you able to try using the conda version rather than the module to see if that works for you?

**Comment by wshropshire** [comment]
I have a conda environment set up on my MacBook Pro, however, given the computational time of prank-msa, let alone mafft, it would be preferable to set it up on the HPC, which my institute is not in favor of setting up. We currently version control using module files. I have panaroo installed locally as well, and when I updated the conda packages, I cannot find prank in the bin directory nor is it in my $PATH.

**Comment by gtonkinhill** [comment]
To check whether this solves your issue without having to run everything, I've copied the problem gene fasta below. If things are working you should be able to `prank -d=dnaA.fasta -o=dnaA -f=8 -codon`

At the moment prank is not bundled with the conda install so you would need to run `conda install -c bioconda prank` after installing panaroo

[dnaA.fasta.zip](https://github.com/gtonkinhill/panaroo/files/4824685/dnaA.fasta.zip)

**Comment by wshropshire** [comment]
I attempted to run prank in my conda environment and it worked so yes, it appears to solve the issue when run locally. I also recapitulated the error when running prank-170427 with the version downloaded. Nevertheless, we don't have conda installed on our HPC and that is the only way to feasibly run a pan-genome analysis. Looks like this issue has been brought up recently in their GitHub and hasn't been resolved.

**Comment by wshropshire** [comment]
Found a (hopeful) solution. The development branch version of prank (prank-170703) does not throw this error. I'm assuming the conda recipe package which lists 170427-1 and 170427-2 uses one of these development branch versions that are not the stable version. Anyways, this should solve future problems hopefully! I would perhaps make a note of this on the installation page. Thanks again for looking into this!

**Comment by gtonkinhill** [comment]
I've updated the conda recipe to include `prank` which should resolve this.
