### ISSUE TITLE
Nonsense mutations

### ISSUE THREAD

**Issue by moorembioinfo** [gtonkinhill/panaroo#65]
Hi, 

First of all, very excited about panaroo! 

I'm just wondering how premature stop codons are dealt with? If they are present are they output in the gene alignments and are those genes designated absent in the gene pres/abs? 

Thanks for advance for any help with this!

**Comment by moorembioinfo** [comment]
Thanks for getting back to me! So my gff were generated with prokka. Does that mean any of those flagged pseudogenes (such as containing premature stop codons compared with their presumably functional homologs) will automatically be marked absent by panaroo in the pres/abs matrix?

I want to run an association for presence/absence but also to make sure those with premature stops are marked absent

Thanks, 

Matt

**Comment by gtonkinhill** [comment]
Prokka input should not result in pseudogenes being included in the graph. However, it is possible that panaroo will refind a pseudogene and include it in the `gene_presence_absence.csv` output. These will be flagged with `_stop` and would currently need to be filtered out manually. I am planning to add in a couple of scripts for performing common manipulations on the presence/absence files but haven't yet had the chance.

**Comment by moorembioinfo** [comment]
Thanks so much for the information, that's everything I need. Congrats again on the software too, it's all running smoothly!

**Comment by kneubehl** [comment]
Did the script to remove the refound pseudogenes get added yet? I am finding this is a problem for me as well. Thanks.

**Comment by gtonkinhill** [comment]
Not quite yet. I will attempt to add this for the next release.

**Comment by gtonkinhill** [comment]
This has now been added in 7a15f1b464032110c4c98a1e0f38dc1f650e848b. The documentation for the new script can be found [here](https://gtonkinhill.github.io/panaroo/#/post/filter)

**Comment by kneubehl** [comment]
Awesome thanks!


Regards,


Alex Kneubehl

PhD Candidate

Laboratory of Dr. Job Lopez
Vector Biology and Bacterial Pathogens Lab

Department of Pediatrics

National School of Tropical Medicine at
Baylor College of Medicine

Twitter: @AlexKneubehl




________________________________
