### ISSUE TITLE
Typo in --edge-support-threshold

### ISSUE THREAD

**Issue by milnus** [gtonkinhill/panaroo#66]
Hi,
I believe a 'd' has snuck its way into the description of the '--edge-support-thesholds' parameter:

```
--edge_support_threshold EDGE_SUPPORT_THRESHOLD
                        minimum support required to keep an`d` edge that has
                        been flagged as a possible mis-assembly
```

**Comment by milnus** [comment]
Another thing is that `--len_dif_percent` is described to have a default of 0.95. However in `set_default_arg.py` the argument is det to 0.98 for all modes.

**Comment by gtonkinhill** [comment]
Thanks for pointing these out. I had meant to include the fix for the typo in the latest release but managed to forget. I've pushed both these corrections to master (6d030657625c96c383b891dc1f1c12e69eafc89d) so they will be updated in the next release.
