### ISSUE TITLE
error when generating network

### ISSUE THREAD

**Issue by stemicha** [gtonkinhill/panaroo#68]
Dear Panaroo-Team,

thanks for providing Panaroo.

I installed Panaroo using Conda in an extra environment.

using:

`conda create -n panaroo`
`conda activate panaroo`
`conda install -c conda-forge -c bioconda -c defaults panaroo`

The installation went flawless but when using Panaroo I got an error when generating the network.

panaroo -i *.gff -o results --clean-mode strict -t 5

pre-processing gff3 files...
running cmd: cd-hit -T 5 -i results/combined_protein_CDS.fasta -o results/combined_protein_cdhit_out.txt -c 0.98 -s 0.98 -aL 0.0 -AL 99999999 -aS 0.0 -AS 99999999 -M 0 -d 999 -g 1 -n 2

Program: CD-HIT, V4.8.1, Oct 26 2019, 12:15:38
______________  
Command: cd-hit -T 5 -i results/combined_protein_CDS.fasta -o
         results/combined_protein_cdhit_out.txt -c 0.98 -s 0.98
         -aL 0.0 -AL 99999999 -aS 0.0 -AS 99999999 -M 0 -d 999
         -g 1 -n 2
______________  
Started: Wed Aug 12 08:34:33 2020
______________  
Output
______________                          
Option -T is ignored: multi-threading with OpenMP is NOT enabled!
Your word length is 2, using 5 may be faster!
total seq: 84047
longest and shortest : 10746 and 19
Total letters: 24965028
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 35M
Buffer          : 1 X 13M = 13M
Table           : 1 X 1M = 1M
Miscellaneous   : 1M
Total           : 51M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 243373000

comparing sequences from          0  to      84047
..........    10000  finished       1308  clusters
..........    20000  finished       2361  clusters
..........    30000  finished       3499  clusters
..........    40000  finished       4681  clusters
..........    50000  finished       6130  clusters
..........    60000  finished       7580  clusters
..........    70000  finished       9273  clusters
..........    80000  finished      11347  clusters
....
    84047  finished      12863  clusters

Approximated maximum memory consumption: 65M
writing new database
writing clustering information
program completed !

Total CPU time 38.31
generating initial network...
Traceback (most recent call last):
  File "/Users/stephanmichalik/miniconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/Users/stephanmichalik/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/__main__.py", line 292, in main
    all_dna=args.all_seq_in_graph)
  File "/Users/stephanmichalik/miniconda3/envs/panaroo/lib/python3.7/site-packages/panaroo/generate_network.py", line 70, in generate_network
    current_cluster = seq_to_cluster[id]
KeyError: '18_0_2640'

**Comment by gtonkinhill** [comment]
Hi, thanks for bringing this to our attention.

Would it be possible to share a subset of the gff files that reproduces this issue? It would make identifying the problem much easier.

My email address is `gerry.tonkin-hill@sanger.ac.uk` if you would prefer to share files via email.

**Comment by gtonkinhill** [comment]
Hi, thanks very much for sending the example gff files.

It looks like this is caused by some of your annotations being labeled with `ID1=` and `ID2=` rather than the expected `ID=` I've copied an example below

```
NC_017763       NCBI    CDS     2362234 2362302 .       +       .       ID1=SAEMRSA15_21870
```

One solution to this is to remove the additional annotation and relabel the first annotation to `ID=`

Alternatively, you can remove all annotations with this issue using grep

```
grep -v "ID[123]=" old.gff > new.gff
```

I will try and improve the way panaroo handles these in the next release by either improving the error message or automatically taking the first annotation.

**Comment by stemicha** [comment]
Thank you now it works!!

best wishes,

Stephan

_______________________________________________________________________________________________________________

Dr. rer. nat. Stephan Michalik
Scientist / Data Scientist
Department of Functional Genomics, University Medicine Greifswald
p:	+49 3834 420-5821  m: +49 172 3138731
f:	+49 3834 8622636
a:	Felix-Hausdorff-Str. 8, 17487 Greifswald, Germany
w:	www.functional-genomics.de <http://www.functional-genomics.de/>  e: stephan.michalik@uni-greifswald.de <mailto:stephan.michalik@uni-greifswald.de>
