### ISSUE TITLE
No core alignment file

### ISSUE THREAD

**Issue by Virome1** [gtonkinhill/panaroo#70]
Does panaroo produce a core alignment file similar to Roary? Or is my output missing it?

**Comment by nzmacalasdair** [comment]
Hello,

Like roary, panaroo has the option of producing a core genome alignment file, either by aligning just the core genome or the entire pan-genome. You can specify either of these options with `-a core` or `-a pan` when running panaroo. If `-a` is not specified, then no alignment will be produced. You can select which multiple sequence alignment software you would like to use with `--aligner`. 

Sometimes, particularly on large datasets, it can be helpful to run the pan-genome inference and core genome alignment steps seperately. We provide a secondary application `panaroo-msa` which should allow you to run the core genome alignment analysis after having already inferred the pangenome (though if you have installed panaroo manually from the git repository, and not through conda, you will likely need to use the script `panaroo-msa-runner.py`. This seems like it is probably the best option in your case if you have already run the pan-genome analysis step in panaroo. It uses the same alignment options as panaroo does.

Let us know if you encounter any further problems!
