### ISSUE TITLE
Issue with collapsing genes 

### ISSUE THREAD

**Issue by shrutikutmutia** [gtonkinhill/panaroo#71]
Hi, I am trying to run panaroo for 138 genomes out of which a 10 are my lab isolates (all bacillus).
I downloaded reference fasta files from ncbi. I ran panaroo_qc followed by prokka for all the genomes. There seems to be a problem with a random gene id every time i run it. A key error is shown. I tried to run the tool on a subset of genomes and it works just fine. 
Please help me with the error 
Iteration:  3
Iteration:  4
collapse gene families...

Traceback (most recent call last):
  File "/cm/shared/apps/devel/anaconda/3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/cm/shared/apps/devel/anaconda/3/envs/panaroo/lib/python3.7/site-packages/panaroo/__main__.py", line 340, in main
    quiet=(not args.verbose))
  File "/cm/shared/apps/devel/anaconda/3/envs/panaroo/lib/python3.7/site-packages/panaroo/clean_network.py", line 141, in collapse_families
    seqid_to_index[sid] = centroid_to_index[seqid_to_centroid[sid]]
KeyError: '13_1_3982'

The results folder has files with the gene ids

(base) [shruti@ln-0001 results2]$ grep "13_1_3982" *
combined_DNA_CDS.fasta:>13_1_3982
combined_protein_cdhit_out.txt:>13_1_3982
combined_protein_cdhit_out.txt.clstr:0	30aa, >13_1_3982... *
combined_protein_CDS.fasta:>13_1_3982

**Comment by gtonkinhill** [comment]
Hi, are you using annotation files from NCBI? These often include annotations that are not valid with Panaroo. 

The package includes a script that can be used to filter these annotations out prior to running Panaroo `scripts/convert_refseq_to_prokka_gff.py`

As a number of others have run into this issue (#67) I am planning to include an option to do this automatically soon.
