### ISSUE TITLE
Error when reading GFF files from GenBank

### ISSUE THREAD

**Issue by flass** [gtonkinhill/panaroo#73]
Hi,

I go this issue when trying to process a bunch of genome assemblies including some that where directly downloaded from the NCBI.

It appears that `panaroo` cannot digest GFF files coming from GenBank as I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/panaroo/__main__.py", line 273, in main
    args.n_cpu)
  File "/usr/local/lib/python3.7/site-packages/panaroo/prokka.py", line 229, in process_prokka_input
    raise RuntimeError("Error reading prokka input!")
RuntimeError: Error reading prokka input!
```
(the error was actually a bit longer when including the report of the error handling by master process, but i don't think that's relevant here)

this was obtained using `panaroo` version 1.2.3 (from the module installed on the Sanger farm).

One example of GFF file that fails is to be found in this assembly: https://www.ncbi.nlm.nih.gov/assembly/GCA_009746685.1

Do you have any suggestion of how this could be addressed? 
Is Panaroo only expecting GFF files as produced by Prokka? I used the the GenBank version of the assembly; do you think it would work better if using the RefSeq annotation?

Thank you in advance for the help.

Florent

**Comment by gtonkinhill** [comment]
Hi Florent,

Yes, panaroo does occasionally throw errors when using GFF files from GenBank and/or RefSeq. This is due to some of the NCBI annotations including genes that are invalid with panaroo. This is often because they include stop codons in the middle of the gene.

A number of people have run into this issue so I am planning on adding an optional flag to filter these annotations in the main pipeline. I will hopefully have this done in the next couple of weeks. In the mean time the package includes a script that can be run separately to clean up these GFF files.

`panaroo/scripts/convert_refseq_to_prokka_gff.py`

**Comment by flass** [comment]
Hi Gerry,

thanks for the suggestion. I tried the script (using the last version from the git repo) but I get an error:
```
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
from: too many arguments
from: too many arguments
/nfs/users/nfs_f/fl4/software/panaroo/scripts/convert_refseq_to_prokka_gff.py: line 8: syntax error near unexpected token `('
/nfs/users/nfs_f/fl4/software/panaroo/scripts/convert_refseq_to_prokka_gff.py: line 8: `def clean_gff_string(gff_string):'
```
Am I missing some environment that is required to execute the script? or is this just a syntax error in the python script?

I tried this with both these environments:
- the base environment from the Sanger farm
- a Conda environment with Python 3.8 as default and Biopython available

Sorry if I'm missing something obvious!

Cheers,
Florent

**Comment by aweimann** [comment]
Hi Florent, You might need to invoke the script with the python interpreter:
```python  /nfs/users/nfs_f/fl4/software/panaroo/scripts/convert_refseq_to_prokka_gff.py```

**Comment by flass** [comment]
ah sorry I should have thought of that myself! I was confused by the fact that the script is provided as an executable file so I was assuming it would know the right interpreter by itself.
I could suggest adding a shebang like `#!/usr/bin/env python3` at the beginning of the script, or to not make the script executable to avoid that mistake.
Trying with the Python interpreter, I still got errors linked to missing packages in the environment; I solved that issue by installing the Conda environment specific to panaroo (https://anaconda.org/bioconda/panaroo).
This script now works fine.

**Comment by flass** [comment]
I confirm that processing the GFF files with the `convert_refseq_to_prokka_gff.py` script allowed me to circumvent the issue. Thanks again.
