### ISSUE TITLE
Way to turn trimming off?

### ISSUE THREAD

**Issue by kneubehl** [gtonkinhill/panaroo#77]
Hi there,

I am trying to run panaroo on some genomes that I have that are 1 replicon = 1 contig. The genomes have lots of linear plasmids 3-12 including a linear chromosome. Should I be concerned with the trimming step since the ends of the linear plasmids are real and not the result of a fragmented assembly? Is there a way to turn this off or limit the trimming, it doesn't appear so in the run options.

**Comment by gtonkinhill** [comment]
Hi,

Yes, I would suggest running Panaroo in its 'sensitive' mode. This turns off most trimming. It can be run as

```
panaroo -i *.gff -o panaroo_out --clean-mode sensitive
```

alternatively the parameters `--min_trailing_support` and `--trailing_recursive` allow for finer grained control over when genes are trimmed. Setting both to zero will effectively turn off trimming.

**Comment by kneubehl** [comment]
Thanks for the info! I ran panaroo with all other parameters unmodified (except --remove-invalid-genes since I used NCBI PGAP to annotate and converted to Prokka-style .gff3 format per your conversion script) --clean-mode strict 'vanilla' (no changes to --min_trailing_support and --trailing_recursive), --clean-mode strict with --min_trailing_support 0 and --trailing_recursive 0 so no trimming, and --clean-mode sensitive. Strict vanilla: 760core, 0score, 811shell, 422cloud genes.  Strict no trimming: 760core, 0score, 814shell, 2547cloud genes. Sensitive: 760core, 0score, 815 shell, 2547 cloud genes. So panaroo is pretty confident in everything but the cloud genes as I would expect however with no trimming with the strict mode I should expect spurious assignments still? Without trimming does strict mode still require the 'present in 5% of genomes' evidence or does setting --min_trailing_support and --trailing_recursive effectively make --clean-mode strict = --clean-mode sensitive? Thanks for the help!

**Comment by gtonkinhill** [comment]
Turning off trimming will give fairly similar results to running panaroo in its sensitive mode. The main remaining difference is that in the sensitive mode the `--remove_by_consensus` parameter is set to `false`. In strict mode if a gene is refound in more genomes than it was originally identified it is flagged as spurious and removed. This is turned off by default in the sensitive mode.

**Comment by kneubehl** [comment]
Thanks for the help!!
