### ISSUE TITLE
Rerunning to get just the core-gene alignment

### ISSUE THREAD

**Issue by jamiethompson77** [gtonkinhill/panaroo#81]
I ran panaroo and aligned all genes (- pan), but now I'd like an alignment of just core genes.  Is there a way to run the core alignment with existing panaroo output, without having to start over?

**Comment by gtonkinhill** [comment]
Hi,

Yes, the `panaroo-msa` function should allow you to do this. It can be run as

```
panaroo-msa -a core -o panaroo_output_directory
```

This will avoid you having to re-run the main panaroo algorithm but it will re-generate the core MSAs rather than using the ones from the pan alignment.

**Comment by jamiethompson77** [comment]
Thank you, that's great.
