### ISSUE TITLE
Provide core gene alignments

### ISSUE THREAD

**Issue by oschwengers** [gtonkinhill/panaroo#85]
Hi,
thanks a lot for this wonderful potential replacement for Roary which is not actively maintained anymore.

Would it be possible to create a core genome alignment just like Roary does (`core_gene_alignment.aln`) for subsequent tree calculations?
Or is it already implemented and I just missed it?

Best regards!

**Comment by nzmacalasdair** [comment]
Hello! You should be able to create core genome alignments, like roary, with the `-a core` option when running panaroo. It's also possible to specify the aligner used as well. 

If you've already run the pangenome inference step of panaroo and would like to create a core or pan genome alignment from that run, you can use panaroo-msa (or panaroo-msa-runner.py if you have installed panaroo by cloning the github) to create alignments from a completed run.

Hope this helps, let us know if you run into any further issues!

**Comment by oschwengers** [comment]
Hello, and thanks for the hint. One `prank` process exited != 0 and thus, there was no core alignment. I've tried it via `panaroo-msa --aligner mafft` which worked as expected.
