### ISSUE TITLE
Just a question. 

### ISSUE THREAD

**Issue by martinastoycheva** [gtonkinhill/panaroo#88]
Is there an easy way of getting the gene frequency information from the panaroo output. I mean how many singletons, doubletons...core. 

Thank you!

**Comment by gtonkinhill** [comment]
Hi,

This currently isn't included as part of the panaroo code but can be achieved fairly easily using R and the `gene_presence_absence.Rtab` file. I've had a go at a very simple example below.

```
pa <- read.table("gene_presence_absence.Rtab", sep = '\t', skip = 1)
freq <- table(rowSums(pa[,2:ncol(pa)]))
plot(as.numeric(names(freq)), freq, type='h')
```

**Comment by martinastoycheva** [comment]
Thank you! That is very helpful!
