### ISSUE TITLE
Not an issue; question about accessory genes

### ISSUE THREAD

**Issue by Virome1** [gtonkinhill/panaroo#92]
Is it possible to get an accessory gene alignment or accessory gene file out of Panaroo? 
Thanks

**Comment by nzmacalasdair** [comment]
Hi, thanks for getting in touch.

Panaroo will output an alignment of every gene in the pan-genome with the option `-a pan`, from this you can then manually concatenate any subset of core or accessory genes. 

By default, panaroo should also generate a  `pan_genome_reference.fa` file which contains the reference sequence for each gene in the pangenome. 

Are these the types of files you're looking for?
