### ISSUE TITLE
Question about pangenome accumulation curve

### ISSUE THREAD

**Issue by smb20200615** [gtonkinhill/panaroo#95]
Hello.

I was wondering if there is a way to plot the pangenome accumulation curve (numb genes vs numb genomes) similar to those produced by create_pan_genome_plots.R in rorary using the output of your tool. I know there is an option for IMG models etc but I am simply interested in a simple pangenome accumulation curve plot.

Many thanks

**Comment by gtonkinhill** [comment]
Hi,

I generally try to discourage the use of pangenome accumulation curves as they fail to account for the underlying genome diversity, sampling bias and annotation errors.

However, there is script included in `panaroo` to generate these curves. You will need to have downloaded the panaroo [repository](https://github.com/gtonkinhill/panaroo) and the script can then be run as

```
python ~/panaroo/post-plot-runner.py --graph_type acc -i gene_presence_absence.Rtab -o ./output_dir/
```

**Comment by smb20200615** [comment]
Thank you so much for your guidance! 

I get the following error:

"panaroo/generate_abundance_plots.py", line 15, in read_presence_absence
    sample_names = matrix_txt[0, 15:]
IndexError: too many indices for array

I know it is hard to tell from the error message but would you have any hints for what could be going on?

**Comment by gtonkinhill** [comment]
Sorry, it's been a while since I ran this script. It should work with the Roary formatted csv file. That is

```
python ~/panaroo/post-plot-runner.py --graph_type acc -i gene_presence_absence_roary.csv -o ./output_dir/
```

**Comment by smb20200615** [comment]
This worked beautifully. Thank you so so much for your timely and super helpful guidance!
