### ISSUE TITLE
Clustering tool suggestion

### ISSUE THREAD

**Issue by apredeus** [gtonkinhill/panaroo#96]
Hello Gerry, 

Am I right to assume that cd-hit clustering of protein sequences is still a rate limiting step for the analysis? 

I came across [mmseqs2](https://github.com/soedinglab/MMseqs2) recently, and it worked really well for an extremely large collection of sequences (I clustered IPG database with about 120M sequences). It might speed up the analysis of big datasets quite a lot.

**Comment by gtonkinhill** [comment]
Hi,

At the moment the main bottleneck is the processing of paralogous sequences. I'm hoping to get some time to improve this soon.

I originally chose not to use mmseqs2 as it calculates local alignments whilst we favour global alignment in Panaroo. This is less of an issue in the initial clustering at high identity but becomes more of an issue at lower identities when collapsing at the gene family level.

**Comment by apredeus** [comment]
I see, thank you for the explanation.
