### ISSUE TITLE
Interpreting presence/absence matrix

### ISSUE THREAD

**Issue by nicolettacommins** [gtonkinhill/panaroo#97]
What does it mean when gene clusters are named like this:

ephD_8~~~~~~ephD_5

or:

bioB_2~~~bioB~~~bioB_1

What does the number of ~ signify?

**Comment by gtonkinhill** [comment]
When a cluster includes sequences with multiple annotations the unique names are concatenated and separated by `~~~` 
If some sequences are not assigned a gene name in the GFF file these are currently included as empty names leading to `~~~~~~` 
I will probably filter these out in the next release.

**Comment by gtonkinhill** [comment]
This has been resolved in 9a092637874b472510bf1456ba6e044cc0824a67 and will be included in the next release.
