### ISSUE TITLE
Error after clustering 

### ISSUE THREAD

**Issue by MartaMatu** [gtonkinhill/panaroo#99]
I installed the new panaroo 1.2.6 using pip on a server. I had issues among the way but I managed to get it to work however straight away after clustering I get this error:  
[
<img width="1164" alt="Screenshot 2021-02-10 at 16 05 35" src="https://user-images.githubusercontent.com/78867256/107536642-e6c93580-6bb9-11eb-8be1-f3fc0aa6b0bb.png">
](url)

Could you please suggest any solution? Should I maybe install the older version?

**Comment by gtonkinhill** [comment]
Hi,

This looks like it could be an issue with the version of networkx you have installed. You should be able to see which version is installed by running 

```
pip freeze
```

It should be at least v2.4
